# Generated by Django 4.2.4 on 2026-02-25 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('SECTION_A_PENDING', 'CONTRACT COMPLIANCE Pending'), ('SECTION_B_PENDING', 'PROCUREMENT DIVISION ACTION Pending'), ('SECTION_C_PENDING', 'OPERATIONS OFFICER RECOMMENDATION Pending'), ('SECTION_D_PENDING', "HUB lead approval for Final payment"), ('COMPLETED', 'APPROVED & COMPLETED')], default='SECTION_A_PENDING', max_length=30)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('commodity_type', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('contract_value_currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD')], default='KES', max_length=10)),
                ('contract_value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('designated_program', models.CharField(blank=True, max_length=255)),
                ('initiator_email', models.EmailField(blank=True, max_length=254)),
                ('section_1_email', models.EmailField(blank=True, max_length=254)),
                ('section_2_email', models.EmailField(blank=True, max_length=254)),
                ('section_3_email', models.EmailField(blank=True, max_length=254)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('section_1_data', models.JSONField(blank=True, default=dict)),
                ('section_1_signature', models.TextField(blank=True)),
                ('section_2_data', models.JSONField(blank=True, default=dict)),
                ('section_2_signature', models.TextField(blank=True)),
                ('section_3_data', models.JSONField(blank=True, default=dict)),
                ('section_3_signature', models.TextField(blank=True)),
                ('supervisor_data', models.JSONField(blank=True, default=dict)),
                ('supervisor_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_link', to='department_form.departmentform')),
            ],
        ),
    ]
