# Generated by Django 4.2.4 on 2026-02-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentform',
            old_name='supplier_name',
            new_name='department_name',
        ),
    ]
