# Generated by Django 4.2.4 on 2026-06-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_add_sso_fields'),
        ('department_form', '0002_rename_supplier_name_departmentform_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A — Initiator'), ('B', 'B — Verifier'), ('C', 'C — Approver'), ('D', 'D — Supervisor')], db_index=True, max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Country tenant override; leave blank for the global reviewer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reviewers', to='account.tenant')),
            ],
            options={
                'ordering': ['section'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='department__section_e9fe83_idx')],
                'unique_together': {('section', 'tenant')},
            },
        ),
    ]
