# Generated by Django 4.2.4 on 2026-05-17 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Ebola Virus Disease"', max_length=200, unique=True)),
                ('family', models.CharField(default='', help_text='e.g. "Filoviridae"', max_length=100)),
                ('r0_min', models.DecimalField(decimal_places=2, default=0, help_text='Lower bound of basic reproduction number', max_digits=4)),
                ('r0_max', models.DecimalField(decimal_places=2, default=0, help_text='Upper bound of basic reproduction number', max_digits=4)),
                ('cfr_min', models.DecimalField(decimal_places=2, default=0, help_text='Case fatality rate lower bound (%)', max_digits=5)),
                ('cfr_max', models.DecimalField(decimal_places=2, default=0, help_text='Case fatality rate upper bound (%)', max_digits=5)),
                ('incubation_days_min', models.PositiveIntegerField(default=0, help_text='Minimum incubation period in days')),
                ('incubation_days_max', models.PositiveIntegerField(default=0, help_text='Maximum incubation period in days')),
                ('transmission_modes', models.JSONField(default=list, help_text='List of transmission modes, e.g. ["contact", "droplet", "fomite"]')),
                ('vaccine_available', models.BooleanField(default=False, help_text='Whether an approved vaccine exists for this pathogen')),
                ('antiviral_available', models.BooleanField(default=False, help_text='Whether approved antivirals/therapeutics exist')),
                ('profile_json', models.JSONField(default=dict, help_text='Extended profile: strain variants, natural hosts, reservoir species, trigger conditions, spillover score, IHR/OIE status, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutbreakHistoricalEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('country_iso3', models.CharField(default='', help_text='ISO3 country code', max_length=3)),
                ('year_start', models.PositiveIntegerField(help_text='Year the episode started')),
                ('year_end', models.PositiveIntegerField(blank=True, help_text='Year the episode ended (null if same as start)', null=True)),
                ('cases', models.PositiveIntegerField(default=0, help_text='Total confirmed + probable cases')),
                ('deaths', models.PositiveIntegerField(default=0, help_text='Total deaths')),
                ('response_summary', models.TextField(default='', help_text='Brief summary of the response. Manually curated only.')),
                ('lessons', models.TextField(default='', help_text='Key lessons learned. Manually curated only.')),
                ('source_urls', models.JSONField(default=list, help_text='List of source URLs (WHO DON, published papers, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_episodes', to='outbreak.pathogen')),
            ],
            options={
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(help_text='ISO 3166-1 alpha-3 for the primary affected country', max_length=3)),
                ('regions', models.JSONField(default=list, help_text='List of affected admin-1/admin-2 region identifiers')),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the outbreak was declared or first detected')),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('confirmed', 'Confirmed'), ('contained', 'Contained'), ('closed', 'Closed')], default='suspected', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('lead_focal_point', models.CharField(default='', help_text='Name or role of the lead focal point', max_length=200)),
                ('summary', models.TextField(default='', help_text='Brief narrative summary of the outbreak situation')),
                ('neighbor_iso3s', models.JSONField(default=list, help_text='ISO3 codes of neighboring countries to monitor for spillover')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbreaks', to='outbreak.pathogen')),
            ],
            options={
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', help_text='ISO3 or admin region to scope this rule (empty = global)', max_length=100)),
                ('severity_threshold', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='high', help_text='Minimum event severity to trigger this rule', max_length=20)),
                ('event_kinds', models.JSONField(default=list, help_text='List of EventKind values to match (empty = all kinds)')),
                ('role', models.CharField(default='', help_text='Recipient role label (e.g. "regional_director", "focal_point")', max_length=100)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=20)),
                ('contact_ids', models.JSONField(default=list, help_text='List of Telegram chat IDs or email addresses')),
                ('template_id', models.CharField(default='', help_text='Notification template identifier', max_length=100)),
                ('auto_send_after_hold', models.BooleanField(default=False, help_text='If True, high-severity notifications auto-send after hold window expires')),
                ('hold_seconds', models.PositiveIntegerField(default=300, help_text='Hold-and-confirm window for high-severity dispatch (seconds)')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pathogen', models.ForeignKey(blank=True, help_text='Filter by pathogen (null = all pathogens)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='outbreak.pathogen')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutbreakEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, help_text='Timestamp of the event (source timestamp if available, else now)')),
                ('source', models.CharField(help_text='Adaptor name that produced this event', max_length=100)),
                ('kind', models.CharField(choices=[('signal', 'Signal'), ('case', 'Case'), ('contact', 'Contact'), ('lab', 'Lab Result'), ('intervention', 'Intervention'), ('resource', 'Resource'), ('mobility', 'Mobility'), ('forecast', 'Forecast'), ('decision', 'Decision'), ('notification', 'Notification'), ('rumor', 'Rumor'), ('burial', 'Unsafe Burial'), ('hcw_infection', 'HCW Infection'), ('silence_anomaly', 'Silence Anomaly'), ('ring_vax', 'Ring Vaccination')], help_text='Event type from the EventKind enum', max_length=30)),
                ('geo', models.CharField(default='', help_text='District/admin-level identifier (never GPS precision)', max_length=100)),
                ('payload_json', models.JSONField(default=dict, help_text='Event payload — schema varies by kind, documented per adaptor')),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, help_text='Confidence score 0.00–1.00', max_digits=3)),
                ('source_ref', models.CharField(default='', help_text='FK reference or URL back to origin row in source system', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbreak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='outbreak.outbreak')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['outbreak', 'ts'], name='evt_outbreak_ts'), models.Index(fields=['outbreak', 'kind', 'ts'], name='evt_outbreak_kind_ts'), models.Index(fields=['outbreak', 'geo', 'ts'], name='evt_outbreak_geo_ts')],
            },
        ),
        migrations.AddConstraint(
            model_name='outbreakevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('source', 'source_ref'), name='unique_event_source_ref'),
        ),
        migrations.AddConstraint(
            model_name='outbreak',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['suspected', 'confirmed'])), fields=('pathogen', 'iso3'), name='unique_active_outbreak_per_pathogen_country'),
        ),
    ]
