# Generated by Django 4.2.4 on 2026-05-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbreak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogen',
            name='monitor_widgets',
            field=models.JSONField(default=list, help_text='List of widget keys the Now pane should render for this pathogen, e.g. ["capacity", "burial", "hcw", "spillover", "deforestation"]. Drives the Pathogen-driven dashboard (T-110).'),
        ),
        migrations.CreateModel(
            name='OutbreakNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('pending_confirm', 'Pending Confirm'), ('sent', 'Sent'), ('acked', 'Acknowledged'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('channel', models.CharField(default='', max_length=20)),
                ('rendered_message', models.TextField(default='')),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='outbreak.outbreakevent')),
                ('outbreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='outbreak.outbreak')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='outbreak.notificationrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outbreak', 'state', 'created_at'], name='outbreak_ou_outbrea_e85b99_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutbreakDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('decision', 'Decision'), ('sitrep', 'Sitrep'), ('note', 'Note')], default='decision', max_length=20)),
                ('title', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=120)),
                ('evidence_event_ids', models.JSONField(default=list)),
                ('citations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='outbreak.outbreak')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outbreak', 'kind', 'created_at'], name='outbreak_ou_outbrea_c664ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='LlmInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ask', 'Q&A'), ('sitrep', 'Sitrep'), ('other', 'Other')], default='ask', max_length=20)),
                ('question', models.TextField(default='')),
                ('grounding_summary', models.TextField(default='')),
                ('raw_response', models.TextField(default='')),
                ('final_answer', models.TextField(default='')),
                ('refusal_reason', models.CharField(default='', max_length=120)),
                ('citations_matched', models.JSONField(default=dict)),
                ('canned_query', models.CharField(default='', max_length=80)),
                ('model', models.CharField(default='', max_length=120)),
                ('provider', models.CharField(default='', max_length=40)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbreak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_interactions', to='outbreak.outbreak')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outbreak', 'created_at'], name='outbreak_ll_outbrea_e484f0_idx'), models.Index(fields=['source', 'created_at'], name='outbreak_ll_source_2fe541_idx')],
            },
        ),
    ]
