# Generated by Django 4.2.4 on 2026-02-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlink',
            name='target_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
