# Generated by Django 4.2.4 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_form', '0002_alter_formlink_target_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierform',
            name='contract_value_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplierform',
            name='contract_value_currency',
            field=models.CharField(choices=[('KES', 'KES'), ('USD', 'USD')], default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='supplierform',
            name='designated_program',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formlink',
            name='target_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierform',
            name='status',
            field=models.CharField(choices=[('SECTION_A_PENDING', 'Section A Pending (Program Officer)'), ('SECTION_B_PENDING', 'Section B Pending (Procurement)'), ('SECTION_C_PENDING', 'Section C Pending'), ('SECTION_D_PENDING', 'Section D Pending (Supervisor)'), ('COMPLETED', 'Completed')], default='SECTION_A_PENDING', max_length=30),
        ),
    ]
