# Generated by Django 4.2.4 on 2026-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_form', '0003_supplierform_contract_value_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierform',
            name='initiator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplierform',
            name='section_1_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplierform',
            name='section_2_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplierform',
            name='section_3_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplierform',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
