# Generated by Django 4.2.4 on 2026-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_form', '0004_supplierform_initiator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierform',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
