# Generated by Django 4.2.4 on 2026-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_form', '0005_alter_supplierform_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierform',
            name='status',
            field=models.CharField(choices=[('SECTION_A_PENDING', 'CONTRACT COMPLIANCE Pending'), ('SECTION_B_PENDING', 'PROCUREMENT DIVISION ACTION Pending'), ('SECTION_C_PENDING', 'OPERATIONS OFFICER RECOMMENDATION Pending'), ('SECTION_D_PENDING', 'HUB lead approval for Final payment'), ('COMPLETED', 'APPROVED & COMPLETED')], default='SECTION_A_PENDING', max_length=30),
        ),
    ]
