# Generated by Django 4.2.4 on 2026-06-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_add_sso_fields'),
        ('supplier_form', '0006_alter_supplierform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A — Contract Compliance'), ('B', 'B — Procurement Division'), ('C', 'C — Operations Officer'), ('D', 'D — Hub Lead')], db_index=True, max_length=1)),
                ('ordinal', models.PositiveSmallIntegerField(help_text='Position on the bench for this section (1 = primary reviewer).')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Country tenant override; leave blank for the global bench.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_reviewers', to='account.tenant')),
            ],
            options={
                'ordering': ['section', 'ordinal'],
                'indexes': [models.Index(fields=['section', 'is_active', 'ordinal'], name='supplier_fo_section_4b7b3f_idx')],
                'unique_together': {('section', 'ordinal', 'tenant')},
            },
        ),
    ]
