# Generated by Django 4.2.4 on 2026-06-03 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitrepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sitrep_number', models.TextField(help_text='SITREP serial number (e.g. No. 001)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SitrepReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitrep_number', models.TextField(unique=True)),
                ('reporting_period', models.TextField(blank=True, default='')),
                ('date_of_issue', models.TextField(blank=True, default='')),
                ('data_cutoff', models.TextField(blank=True, default='')),
                ('classification', models.TextField(blank=True, default='WHO / FOR OFFICIAL USE — INTERNAL COORDINATION')),
                ('geographic_scope', models.TextField(blank=True, default='WHO African Region — 47 Member States')),
                ('triggering_event', models.TextField(blank=True, default='')),
                ('prepared_by', models.TextField(blank=True, default='')),
                ('cleared_by', models.TextField(blank=True, default='')),
                ('next_issue', models.TextField(blank=True, default='')),
                ('population_in_screening', models.TextField(blank=True, default='0')),
                ('high_risk_poe', models.TextField(blank=True, default='0')),
                ('referred', models.TextField(blank=True, default='0')),
                ('isolated', models.TextField(blank=True, default='0')),
                ('suspected', models.TextField(blank=True, default='0')),
                ('selected_country', models.TextField(blank=True, default='')),
                ('checklist_responses', models.JSONField(blank=True, default=dict, help_text='Map of checklist item key → "YES" / "NO" / null')),
                ('action_points', models.JSONField(blank=True, default=list, help_text='Array of {action: str, pillar: str}')),
                ('planned_actions', models.TextField(blank=True, default='')),
                ('key_challenges', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='sitrep_form.sitreplink')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SitrepFieldEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('edited_by', models.CharField(blank=True, default='Anonymous', max_length=255)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='sitrep_form.sitrepreport')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
