# Generated by Django 4.2.4 on 2025-11-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_on_table', models.CharField(max_length=100, unique=True)),
                ('n', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('subgroup_of_hazards', models.CharField(blank=True, max_length=100, null=True)),
                ('main_type_of_hazard', models.CharField(blank=True, max_length=100, null=True)),
                ('hazard', models.CharField(blank=True, max_length=100, null=True)),
                ('health_consequences', models.CharField(blank=True, max_length=100, null=True)),
                ('scale', models.CharField(blank=True, max_length=100, null=True)),
                ('geographical_area', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('seasonality', models.CharField(blank=True, max_length=100, null=True)),
                ('jan', models.CharField(blank=True, max_length=100, null=True)),
                ('feb', models.CharField(blank=True, max_length=100, null=True)),
                ('mar', models.CharField(blank=True, max_length=100, null=True)),
                ('apr', models.CharField(blank=True, max_length=100, null=True)),
                ('may', models.CharField(blank=True, max_length=100, null=True)),
                ('jun', models.CharField(blank=True, max_length=100, null=True)),
                ('jul', models.CharField(blank=True, max_length=100, null=True)),
                ('aug', models.CharField(blank=True, max_length=100, null=True)),
                ('sep', models.CharField(blank=True, max_length=100, null=True)),
                ('oct', models.CharField(blank=True, max_length=100, null=True)),
                ('nov', models.CharField(blank=True, max_length=100, null=True)),
                ('dec', models.CharField(blank=True, max_length=100, null=True)),
                ('likelihood', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=100, null=True)),
                ('vulnerability', models.CharField(blank=True, max_length=100, null=True)),
                ('vulnerability_details', models.CharField(blank=True, max_length=100, null=True)),
                ('coping_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('coping_capacity_details', models.CharField(blank=True, max_length=100, null=True)),
                ('governance_and_resouces', models.CharField(blank=True, max_length=100, null=True)),
                ('health_sector_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('non_health_sector_capcity', models.CharField(blank=True, max_length=100, null=True)),
                ('commuty_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('resources', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
