# Generated by Django 4.2.4 on 2026-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardata', '0003_alter_stardata_apr_alter_stardata_aug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarCandlestick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('month_num', models.IntegerField()),
                ('open_val', models.FloatField()),
                ('high_val', models.FloatField()),
                ('low_val', models.FloatField()),
                ('close_val', models.FloatField()),
                ('month_key', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['hazard', 'country', 'year'], name='stardata_st_hazard_8a9543_idx'), models.Index(fields=['month_key'], name='stardata_st_month_k_6bd1ff_idx')],
            },
        ),
    ]
