# Generated by Django 4.2.4 on 2026-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardata', '0004_starcandlestick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stardata',
            name='apr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='aug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='commuty_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='confidence_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='coping_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='coping_capacity_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='exposure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='feb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='frequency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='geographical_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='governance_and_resouces',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='hazard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='health_consequences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='health_sector_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='jan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='jul',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='jun',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='key_on_table',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='likelihood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='main_type_of_hazard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='mar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='may',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='n',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='non_health_sector_capcity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='nov',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='oct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='risk_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='risk_level_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='scale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='seasonality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='sep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='severity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='start_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='subgroup_of_hazards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='vulnerability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='vulnerability_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stardata',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
