# Generated by Django 4.2.4 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0002_alter_arbovirus_admin_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbovirus',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cholera',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cholerasubnational',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cyclone',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fvd',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fvdpoe',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lassafever',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lassafeverdistrict',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marburg',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meningitis',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meningitiseelimination',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpox',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpoxdistrict',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naturaldisaster',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riftvalleyfever',
            name='national_yn_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
