# Generated by Django 4.2.4 on 2025-11-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0004_alter_cholera_data_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marburg',
            name='data_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marburg',
            name='data_period_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
