# Generated by Django 6.0.2 on 2026-02-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0005_alter_marburg_data_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparednessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_range', models.CharField(max_length=100)),
                ('featured_achievement', models.TextField(blank=True, null=True)),
                ('readiness', models.TextField(blank=True, null=True)),
                ('naphs', models.TextField(blank=True, null=True)),
                ('community_protection', models.TextField(blank=True, null=True)),
                ('workforce_training', models.TextField(blank=True, null=True)),
                ('pandemic_influenza', models.TextField(blank=True, null=True)),
                ('vaccines_research', models.TextField(blank=True, null=True)),
                ('key_figures', models.JSONField(blank=True, default=dict)),
                ('health_security_governance', models.JSONField(blank=True, default=dict)),
                ('health_security_financing', models.JSONField(blank=True, default=dict)),
                ('threats_risks_management', models.JSONField(blank=True, default=dict)),
                ('diseases_under_elimination', models.JSONField(blank=True, default=dict)),
                ('innovative_projects', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
