# Generated by Django 4.2.4 on 2026-02-15 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readiness', '0007_reportmember_preparednessreport_member_reportteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('week_range', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_range', models.CharField(max_length=100, unique=True)),
                ('featured_achievement', models.TextField(blank=True, default='')),
                ('climate_risks', models.TextField(blank=True, default='')),
                ('upcoming_ph_risks', models.TextField(blank=True, default='')),
                ('espar_submission_tracker', models.TextField(blank=True, default='')),
                ('ihr', models.TextField(blank=True, default='')),
                ('pandemic_agreement', models.TextField(blank=True, default='')),
                ('one_health', models.TextField(blank=True, default='')),
                ('pandemic_fund', models.TextField(blank=True, default='')),
                ('threats_risks_management', models.TextField(blank=True, default='')),
                ('espar', models.TextField(blank=True, default='')),
                ('jee', models.TextField(blank=True, default='')),
                ('simex', models.TextField(blank=True, default='')),
                ('ear_aar', models.TextField(blank=True, default='')),
                ('readiness', models.TextField(blank=True, default='')),
                ('naphs', models.TextField(blank=True, default='')),
                ('community_protection', models.TextField(blank=True, default='')),
                ('workforce_training', models.TextField(blank=True, default='')),
                ('pandemic_influenza', models.TextField(blank=True, default='')),
                ('vaccines_research', models.TextField(blank=True, default='')),
                ('cholera', models.TextField(blank=True, default='')),
                ('meningitis', models.TextField(blank=True, default='')),
                ('yellow_fever', models.TextField(blank=True, default='')),
                ('ai_for_preparedness', models.TextField(blank=True, default='')),
                ('reach_africa', models.TextField(blank=True, default='')),
                ('probe_africa', models.TextField(blank=True, default='')),
                ('cbrn', models.TextField(blank=True, default='')),
                ('mass_gathering', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='readiness.weeklyreportlink')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFieldEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('edited_by', models.CharField(blank=True, default='Anonymous', max_length=255)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='readiness.weeklyreport')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
