# Generated by Django 4.2.4 on 2026-02-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0011_weeklyreport_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='is_deleted',
        ),
    ]
