# Generated by Django 4.2.4 on 2026-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0012_remove_weeklyreport_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbovirus',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='arbovirus',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='arbovirus',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='arbovirus',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='arbovirus',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='arbovirus',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholera',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholera',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholera',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholera',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cholera',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholera',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cyclone',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cyclone',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cyclone',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cyclone',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cyclone',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cyclone',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvd',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvd',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvd',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvd',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='fvd',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvd',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafever',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafever',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafever',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafever',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='lassafever',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafever',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marburg',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marburg',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marburg',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marburg',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='marburg',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marburg',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitis',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitis',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitis',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitis',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='meningitis',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitis',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitiseelimination',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitiseelimination',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitiseelimination',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitiseelimination',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='meningitiseelimination',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='meningitiseelimination',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpox',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpox',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpox',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpox',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='mpox',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpox',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='naturaldisaster',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='naturaldisaster',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='naturaldisaster',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='naturaldisaster',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='naturaldisaster',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='naturaldisaster',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='riftvalleyfever',
            name='category_percent_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='riftvalleyfever',
            name='category_percent_country_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='riftvalleyfever',
            name='category_weight_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='riftvalleyfever',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='riftvalleyfever',
            name='h_times_m',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='riftvalleyfever',
            name='weighted_sum_country',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
    ]
