# Generated by Django 4.2.4 on 2026-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0012_remove_weeklyreport_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='featured_achievement_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_reports/images/'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='key_figures_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_reports/images/'),
        ),
    ]
