# Generated by Django 4.2.4 on 2026-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0013_arbovirus_category_percent_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cholerasubnational',
            name='category_percent_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='category_percent_geo_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='category_weight_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cholerasubnational',
            name='weighted_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='category_percent_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='category_percent_geo_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='category_weight_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fvdpoe',
            name='weighted_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='category_percent_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='category_percent_geo_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='category_weight_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lassafeverdistrict',
            name='weighted_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='category_percent_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='category_percent_geo_pct',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='category_weight_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mpoxdistrict',
            name='weighted_sum_geo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cholerasubnational',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
