# Generated by Django 4.2.4 on 2026-02-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0013_weeklyreport_featured_achievement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='featured_achievement_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='key_figures_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
