# Generated by Django 4.2.4 on 2026-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0014_add_geo_fields_to_subnational_models'),
        ('readiness', '0014_alter_weeklyreport_featured_achievement_image_and_more'),
    ]

    operations = [
    ]
