# Generated by Django 4.2.4 on 2026-02-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0015_merge_20260224_0253'),
        ('readiness', '0015_merge_20260225_1108'),
    ]

    operations = [
    ]
