# Generated by Django 4.2.4 on 2026-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0016_merge_20260226_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='one_health',
            field=models.TextField(blank=True, default=''),
        ),
    ]
