# Generated by Django 4.2.4 on 2026-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0017_weeklyreport_one_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='hedrm',
            field=models.TextField(blank=True, default=''),
        ),
    ]
