# Generated by Django 4.2.4 on 2026-04-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0008_alter_arbovirus_national_yn_and_more'),
        ('readiness', '0019_charfield_to_textfield'),
    ]

    operations = [
    ]
