# Generated by Django 4.2.4 on 2026-04-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0019_charfield_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='osl',
            field=models.TextField(blank=True, default=''),
        ),
    ]
