# Generated by Django 4.2.4 on 2026-04-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0020_merge_20260409_1003'),
        ('readiness', '0020_weeklyreport_osl'),
    ]

    operations = [
    ]
