// Automatically generated by odin 1.5.11 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
typedef struct seirdv_internal {
  double *active;
  double beta;
  double *beta_vec;
  double *coverage_vec;
  double *days_active;
  double *days_no_case;
  double *delta;
  int dim_active;
  int dim_beta_vec;
  int dim_coverage_vec;
  int dim_D;
  int dim_days_active;
  int dim_days_no_case;
  int dim_delta;
  int dim_delta_1;
  int dim_delta_2;
  int dim_E;
  int dim_I;
  int dim_ini_D;
  int dim_ini_E;
  int dim_ini_I;
  int dim_ini_R;
  int dim_ini_S;
  int dim_ini_V;
  int dim_lambda;
  int dim_lambda_prod;
  int dim_lambda_prod_1;
  int dim_lambda_prod_2;
  int dim_N;
  int dim_n_E_I;
  int dim_n_I_D;
  int dim_n_I_out;
  int dim_n_I_R;
  int dim_n_S_E;
  int dim_n_S_out;
  int dim_n_S_V;
  int dim_p_S_out;
  int dim_p_S_V;
  int dim_R;
  int dim_rate_S_out;
  int dim_rate_S_V;
  int dim_response_vacc_coverage;
  int dim_S;
  int dim_status;
  int dim_V;
  double gamma;
  double *ini_D;
  double *ini_E;
  double *ini_I;
  double *ini_R;
  double *ini_S;
  double *ini_V;
  double *initial_D;
  double *initial_E;
  double *initial_I;
  double *initial_R;
  double *initial_S;
  double *initial_V;
  double interv_delay;
  double interv_efficacy;
  double interv_release;
  double interv_vacc_coverage;
  double interv_vacc_type;
  double *lambda;
  double *lambda_prod;
  double mu;
  double *N;
  double *n_E_I;
  double *n_I_D;
  double *n_I_out;
  double *n_I_R;
  int n_populations;
  double *n_S_E;
  double *n_S_out;
  double *n_S_V;
  int offset_variable_D;
  int offset_variable_I;
  int offset_variable_R;
  int offset_variable_V;
  double *p_S_out;
  double *p_S_V;
  double *rate_S_out;
  double *rate_S_V;
  double *response_vacc_coverage;
  double sigma;
  double *status;
  double target_size;
  double vacc_coverage;
  double vacc_efficacy;
} seirdv_internal;
seirdv_internal* seirdv_get_internal(SEXP internal_p, int closed_error);
static void seirdv_finalise(SEXP internal_p);
SEXP seirdv_create(SEXP user);
void seirdv_initmod_desolve(void(* odeparms) (int *, double *));
SEXP seirdv_contents(SEXP internal_p);
SEXP seirdv_set_user(SEXP internal_p, SEXP user);
SEXP seirdv_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr);
SEXP seirdv_metadata(SEXP internal_p);
SEXP seirdv_initial_conditions(SEXP internal_p, SEXP step_ptr);
void seirdv_rhs(seirdv_internal* internal, size_t step, double * state, double * state_next, double * output);
void seirdv_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal);
SEXP seirdv_rhs_r(SEXP internal_p, SEXP step, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
void odin_set_dim(SEXP target, int rank, ...);
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim);
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...);
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max);
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required);
int scalar_int(SEXP x, const char * name);
double odin_sum1(double *x, size_t from, size_t to);
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1);
seirdv_internal* seirdv_get_internal(SEXP internal_p, int closed_error) {
  seirdv_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (seirdv_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void seirdv_finalise(SEXP internal_p) {
  seirdv_internal *internal = seirdv_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal->active);
    R_Free(internal->beta_vec);
    R_Free(internal->coverage_vec);
    R_Free(internal->days_active);
    R_Free(internal->days_no_case);
    R_Free(internal->delta);
    R_Free(internal->ini_D);
    R_Free(internal->ini_E);
    R_Free(internal->ini_I);
    R_Free(internal->ini_R);
    R_Free(internal->ini_S);
    R_Free(internal->ini_V);
    R_Free(internal->initial_D);
    R_Free(internal->initial_E);
    R_Free(internal->initial_I);
    R_Free(internal->initial_R);
    R_Free(internal->initial_S);
    R_Free(internal->initial_V);
    R_Free(internal->lambda);
    R_Free(internal->lambda_prod);
    R_Free(internal->N);
    R_Free(internal->n_E_I);
    R_Free(internal->n_I_D);
    R_Free(internal->n_I_out);
    R_Free(internal->n_I_R);
    R_Free(internal->n_S_E);
    R_Free(internal->n_S_out);
    R_Free(internal->n_S_V);
    R_Free(internal->p_S_out);
    R_Free(internal->p_S_V);
    R_Free(internal->rate_S_out);
    R_Free(internal->rate_S_V);
    R_Free(internal->response_vacc_coverage);
    R_Free(internal->status);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP seirdv_create(SEXP user) {
  seirdv_internal *internal = (seirdv_internal*) R_Calloc(1, seirdv_internal);
  internal->active = NULL;
  internal->beta_vec = NULL;
  internal->coverage_vec = NULL;
  internal->days_active = NULL;
  internal->days_no_case = NULL;
  internal->delta = NULL;
  internal->ini_D = NULL;
  internal->ini_E = NULL;
  internal->ini_I = NULL;
  internal->ini_R = NULL;
  internal->ini_S = NULL;
  internal->ini_V = NULL;
  internal->initial_D = NULL;
  internal->initial_E = NULL;
  internal->initial_I = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->initial_V = NULL;
  internal->lambda = NULL;
  internal->lambda_prod = NULL;
  internal->N = NULL;
  internal->n_E_I = NULL;
  internal->n_I_D = NULL;
  internal->n_I_out = NULL;
  internal->n_I_R = NULL;
  internal->n_S_E = NULL;
  internal->n_S_out = NULL;
  internal->n_S_V = NULL;
  internal->p_S_out = NULL;
  internal->p_S_V = NULL;
  internal->rate_S_out = NULL;
  internal->rate_S_V = NULL;
  internal->response_vacc_coverage = NULL;
  internal->status = NULL;
  internal->beta = 0;
  internal->delta = 0;
  internal->gamma = 0;
  internal->ini_D = 0;
  internal->ini_E = 0;
  internal->ini_I = 0;
  internal->ini_R = 0;
  internal->ini_S = 0;
  internal->ini_V = 0;
  internal->interv_delay = 0;
  internal->interv_efficacy = 0;
  internal->interv_release = 0;
  internal->interv_vacc_coverage = 0;
  internal->interv_vacc_type = 1;
  internal->mu = 0;
  internal->n_populations = 1;
  internal->sigma = 0;
  internal->target_size = 0;
  internal->vacc_coverage = 0;
  internal->vacc_efficacy = 0;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, seirdv_finalise);
  UNPROTECT(1);
  return ptr;
}
static seirdv_internal *seirdv_internal_ds;
void seirdv_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  seirdv_internal_ds = seirdv_get_internal(get_desolve_gparms(), 1);
}
SEXP seirdv_contents(SEXP internal_p) {
  seirdv_internal *internal = seirdv_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 89));
  SEXP active = PROTECT(allocVector(REALSXP, internal->dim_active));
  memcpy(REAL(active), internal->active, internal->dim_active * sizeof(double));
  SET_VECTOR_ELT(contents, 0, active);
  SET_VECTOR_ELT(contents, 1, ScalarReal(internal->beta));
  SEXP beta_vec = PROTECT(allocVector(REALSXP, internal->dim_beta_vec));
  memcpy(REAL(beta_vec), internal->beta_vec, internal->dim_beta_vec * sizeof(double));
  SET_VECTOR_ELT(contents, 2, beta_vec);
  SEXP coverage_vec = PROTECT(allocVector(REALSXP, internal->dim_coverage_vec));
  memcpy(REAL(coverage_vec), internal->coverage_vec, internal->dim_coverage_vec * sizeof(double));
  SET_VECTOR_ELT(contents, 3, coverage_vec);
  SEXP days_active = PROTECT(allocVector(REALSXP, internal->dim_days_active));
  memcpy(REAL(days_active), internal->days_active, internal->dim_days_active * sizeof(double));
  SET_VECTOR_ELT(contents, 4, days_active);
  SEXP days_no_case = PROTECT(allocVector(REALSXP, internal->dim_days_no_case));
  memcpy(REAL(days_no_case), internal->days_no_case, internal->dim_days_no_case * sizeof(double));
  SET_VECTOR_ELT(contents, 5, days_no_case);
  SEXP delta = PROTECT(allocVector(REALSXP, internal->dim_delta));
  memcpy(REAL(delta), internal->delta, internal->dim_delta * sizeof(double));
  odin_set_dim(delta, 2, internal->dim_delta_1, internal->dim_delta_2);
  SET_VECTOR_ELT(contents, 6, delta);
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_active));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_beta_vec));
  SET_VECTOR_ELT(contents, 9, ScalarInteger(internal->dim_coverage_vec));
  SET_VECTOR_ELT(contents, 10, ScalarInteger(internal->dim_D));
  SET_VECTOR_ELT(contents, 11, ScalarInteger(internal->dim_days_active));
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_days_no_case));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_delta));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_delta_1));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_delta_2));
  SET_VECTOR_ELT(contents, 16, ScalarInteger(internal->dim_E));
  SET_VECTOR_ELT(contents, 17, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(contents, 18, ScalarInteger(internal->dim_ini_D));
  SET_VECTOR_ELT(contents, 19, ScalarInteger(internal->dim_ini_E));
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->dim_ini_I));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->dim_ini_R));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->dim_ini_S));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->dim_ini_V));
  SET_VECTOR_ELT(contents, 24, ScalarInteger(internal->dim_lambda));
  SET_VECTOR_ELT(contents, 25, ScalarInteger(internal->dim_lambda_prod));
  SET_VECTOR_ELT(contents, 26, ScalarInteger(internal->dim_lambda_prod_1));
  SET_VECTOR_ELT(contents, 27, ScalarInteger(internal->dim_lambda_prod_2));
  SET_VECTOR_ELT(contents, 28, ScalarInteger(internal->dim_N));
  SET_VECTOR_ELT(contents, 29, ScalarInteger(internal->dim_n_E_I));
  SET_VECTOR_ELT(contents, 30, ScalarInteger(internal->dim_n_I_D));
  SET_VECTOR_ELT(contents, 31, ScalarInteger(internal->dim_n_I_out));
  SET_VECTOR_ELT(contents, 32, ScalarInteger(internal->dim_n_I_R));
  SET_VECTOR_ELT(contents, 33, ScalarInteger(internal->dim_n_S_E));
  SET_VECTOR_ELT(contents, 34, ScalarInteger(internal->dim_n_S_out));
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->dim_n_S_V));
  SET_VECTOR_ELT(contents, 36, ScalarInteger(internal->dim_p_S_out));
  SET_VECTOR_ELT(contents, 37, ScalarInteger(internal->dim_p_S_V));
  SET_VECTOR_ELT(contents, 38, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 39, ScalarInteger(internal->dim_rate_S_out));
  SET_VECTOR_ELT(contents, 40, ScalarInteger(internal->dim_rate_S_V));
  SET_VECTOR_ELT(contents, 41, ScalarInteger(internal->dim_response_vacc_coverage));
  SET_VECTOR_ELT(contents, 42, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 43, ScalarInteger(internal->dim_status));
  SET_VECTOR_ELT(contents, 44, ScalarInteger(internal->dim_V));
  SET_VECTOR_ELT(contents, 45, ScalarReal(internal->gamma));
  SEXP ini_D = PROTECT(allocVector(REALSXP, internal->dim_ini_D));
  memcpy(REAL(ini_D), internal->ini_D, internal->dim_ini_D * sizeof(double));
  SET_VECTOR_ELT(contents, 46, ini_D);
  SEXP ini_E = PROTECT(allocVector(REALSXP, internal->dim_ini_E));
  memcpy(REAL(ini_E), internal->ini_E, internal->dim_ini_E * sizeof(double));
  SET_VECTOR_ELT(contents, 47, ini_E);
  SEXP ini_I = PROTECT(allocVector(REALSXP, internal->dim_ini_I));
  memcpy(REAL(ini_I), internal->ini_I, internal->dim_ini_I * sizeof(double));
  SET_VECTOR_ELT(contents, 48, ini_I);
  SEXP ini_R = PROTECT(allocVector(REALSXP, internal->dim_ini_R));
  memcpy(REAL(ini_R), internal->ini_R, internal->dim_ini_R * sizeof(double));
  SET_VECTOR_ELT(contents, 49, ini_R);
  SEXP ini_S = PROTECT(allocVector(REALSXP, internal->dim_ini_S));
  memcpy(REAL(ini_S), internal->ini_S, internal->dim_ini_S * sizeof(double));
  SET_VECTOR_ELT(contents, 50, ini_S);
  SEXP ini_V = PROTECT(allocVector(REALSXP, internal->dim_ini_V));
  memcpy(REAL(ini_V), internal->ini_V, internal->dim_ini_V * sizeof(double));
  SET_VECTOR_ELT(contents, 51, ini_V);
  SEXP initial_D = PROTECT(allocVector(REALSXP, internal->dim_D));
  memcpy(REAL(initial_D), internal->initial_D, internal->dim_D * sizeof(double));
  SET_VECTOR_ELT(contents, 52, initial_D);
  SEXP initial_E = PROTECT(allocVector(REALSXP, internal->dim_E));
  memcpy(REAL(initial_E), internal->initial_E, internal->dim_E * sizeof(double));
  SET_VECTOR_ELT(contents, 53, initial_E);
  SEXP initial_I = PROTECT(allocVector(REALSXP, internal->dim_I));
  memcpy(REAL(initial_I), internal->initial_I, internal->dim_I * sizeof(double));
  SET_VECTOR_ELT(contents, 54, initial_I);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  SET_VECTOR_ELT(contents, 55, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  SET_VECTOR_ELT(contents, 56, initial_S);
  SEXP initial_V = PROTECT(allocVector(REALSXP, internal->dim_V));
  memcpy(REAL(initial_V), internal->initial_V, internal->dim_V * sizeof(double));
  SET_VECTOR_ELT(contents, 57, initial_V);
  SET_VECTOR_ELT(contents, 58, ScalarReal(internal->interv_delay));
  SET_VECTOR_ELT(contents, 59, ScalarReal(internal->interv_efficacy));
  SET_VECTOR_ELT(contents, 60, ScalarReal(internal->interv_release));
  SET_VECTOR_ELT(contents, 61, ScalarReal(internal->interv_vacc_coverage));
  SET_VECTOR_ELT(contents, 62, ScalarReal(internal->interv_vacc_type));
  SEXP lambda = PROTECT(allocVector(REALSXP, internal->dim_lambda));
  memcpy(REAL(lambda), internal->lambda, internal->dim_lambda * sizeof(double));
  SET_VECTOR_ELT(contents, 63, lambda);
  SEXP lambda_prod = PROTECT(allocVector(REALSXP, internal->dim_lambda_prod));
  memcpy(REAL(lambda_prod), internal->lambda_prod, internal->dim_lambda_prod * sizeof(double));
  odin_set_dim(lambda_prod, 2, internal->dim_lambda_prod_1, internal->dim_lambda_prod_2);
  SET_VECTOR_ELT(contents, 64, lambda_prod);
  SET_VECTOR_ELT(contents, 65, ScalarReal(internal->mu));
  SEXP N = PROTECT(allocVector(REALSXP, internal->dim_N));
  memcpy(REAL(N), internal->N, internal->dim_N * sizeof(double));
  SET_VECTOR_ELT(contents, 66, N);
  SEXP n_E_I = PROTECT(allocVector(REALSXP, internal->dim_n_E_I));
  memcpy(REAL(n_E_I), internal->n_E_I, internal->dim_n_E_I * sizeof(double));
  SET_VECTOR_ELT(contents, 67, n_E_I);
  SEXP n_I_D = PROTECT(allocVector(REALSXP, internal->dim_n_I_D));
  memcpy(REAL(n_I_D), internal->n_I_D, internal->dim_n_I_D * sizeof(double));
  SET_VECTOR_ELT(contents, 68, n_I_D);
  SEXP n_I_out = PROTECT(allocVector(REALSXP, internal->dim_n_I_out));
  memcpy(REAL(n_I_out), internal->n_I_out, internal->dim_n_I_out * sizeof(double));
  SET_VECTOR_ELT(contents, 69, n_I_out);
  SEXP n_I_R = PROTECT(allocVector(REALSXP, internal->dim_n_I_R));
  memcpy(REAL(n_I_R), internal->n_I_R, internal->dim_n_I_R * sizeof(double));
  SET_VECTOR_ELT(contents, 70, n_I_R);
  SET_VECTOR_ELT(contents, 71, ScalarInteger(internal->n_populations));
  SEXP n_S_E = PROTECT(allocVector(REALSXP, internal->dim_n_S_E));
  memcpy(REAL(n_S_E), internal->n_S_E, internal->dim_n_S_E * sizeof(double));
  SET_VECTOR_ELT(contents, 72, n_S_E);
  SEXP n_S_out = PROTECT(allocVector(REALSXP, internal->dim_n_S_out));
  memcpy(REAL(n_S_out), internal->n_S_out, internal->dim_n_S_out * sizeof(double));
  SET_VECTOR_ELT(contents, 73, n_S_out);
  SEXP n_S_V = PROTECT(allocVector(REALSXP, internal->dim_n_S_V));
  memcpy(REAL(n_S_V), internal->n_S_V, internal->dim_n_S_V * sizeof(double));
  SET_VECTOR_ELT(contents, 74, n_S_V);
  SET_VECTOR_ELT(contents, 75, ScalarInteger(internal->offset_variable_D));
  SET_VECTOR_ELT(contents, 76, ScalarInteger(internal->offset_variable_I));
  SET_VECTOR_ELT(contents, 77, ScalarInteger(internal->offset_variable_R));
  SET_VECTOR_ELT(contents, 78, ScalarInteger(internal->offset_variable_V));
  SEXP p_S_out = PROTECT(allocVector(REALSXP, internal->dim_p_S_out));
  memcpy(REAL(p_S_out), internal->p_S_out, internal->dim_p_S_out * sizeof(double));
  SET_VECTOR_ELT(contents, 79, p_S_out);
  SEXP p_S_V = PROTECT(allocVector(REALSXP, internal->dim_p_S_V));
  memcpy(REAL(p_S_V), internal->p_S_V, internal->dim_p_S_V * sizeof(double));
  SET_VECTOR_ELT(contents, 80, p_S_V);
  SEXP rate_S_out = PROTECT(allocVector(REALSXP, internal->dim_rate_S_out));
  memcpy(REAL(rate_S_out), internal->rate_S_out, internal->dim_rate_S_out * sizeof(double));
  SET_VECTOR_ELT(contents, 81, rate_S_out);
  SEXP rate_S_V = PROTECT(allocVector(REALSXP, internal->dim_rate_S_V));
  memcpy(REAL(rate_S_V), internal->rate_S_V, internal->dim_rate_S_V * sizeof(double));
  SET_VECTOR_ELT(contents, 82, rate_S_V);
  SEXP response_vacc_coverage = PROTECT(allocVector(REALSXP, internal->dim_response_vacc_coverage));
  memcpy(REAL(response_vacc_coverage), internal->response_vacc_coverage, internal->dim_response_vacc_coverage * sizeof(double));
  SET_VECTOR_ELT(contents, 83, response_vacc_coverage);
  SET_VECTOR_ELT(contents, 84, ScalarReal(internal->sigma));
  SEXP status = PROTECT(allocVector(REALSXP, internal->dim_status));
  memcpy(REAL(status), internal->status, internal->dim_status * sizeof(double));
  SET_VECTOR_ELT(contents, 85, status);
  SET_VECTOR_ELT(contents, 86, ScalarReal(internal->target_size));
  SET_VECTOR_ELT(contents, 87, ScalarReal(internal->vacc_coverage));
  SET_VECTOR_ELT(contents, 88, ScalarReal(internal->vacc_efficacy));
  SEXP nms = PROTECT(allocVector(STRSXP, 89));
  SET_STRING_ELT(nms, 0, mkChar("active"));
  SET_STRING_ELT(nms, 1, mkChar("beta"));
  SET_STRING_ELT(nms, 2, mkChar("beta_vec"));
  SET_STRING_ELT(nms, 3, mkChar("coverage_vec"));
  SET_STRING_ELT(nms, 4, mkChar("days_active"));
  SET_STRING_ELT(nms, 5, mkChar("days_no_case"));
  SET_STRING_ELT(nms, 6, mkChar("delta"));
  SET_STRING_ELT(nms, 7, mkChar("dim_active"));
  SET_STRING_ELT(nms, 8, mkChar("dim_beta_vec"));
  SET_STRING_ELT(nms, 9, mkChar("dim_coverage_vec"));
  SET_STRING_ELT(nms, 10, mkChar("dim_D"));
  SET_STRING_ELT(nms, 11, mkChar("dim_days_active"));
  SET_STRING_ELT(nms, 12, mkChar("dim_days_no_case"));
  SET_STRING_ELT(nms, 13, mkChar("dim_delta"));
  SET_STRING_ELT(nms, 14, mkChar("dim_delta_1"));
  SET_STRING_ELT(nms, 15, mkChar("dim_delta_2"));
  SET_STRING_ELT(nms, 16, mkChar("dim_E"));
  SET_STRING_ELT(nms, 17, mkChar("dim_I"));
  SET_STRING_ELT(nms, 18, mkChar("dim_ini_D"));
  SET_STRING_ELT(nms, 19, mkChar("dim_ini_E"));
  SET_STRING_ELT(nms, 20, mkChar("dim_ini_I"));
  SET_STRING_ELT(nms, 21, mkChar("dim_ini_R"));
  SET_STRING_ELT(nms, 22, mkChar("dim_ini_S"));
  SET_STRING_ELT(nms, 23, mkChar("dim_ini_V"));
  SET_STRING_ELT(nms, 24, mkChar("dim_lambda"));
  SET_STRING_ELT(nms, 25, mkChar("dim_lambda_prod"));
  SET_STRING_ELT(nms, 26, mkChar("dim_lambda_prod_1"));
  SET_STRING_ELT(nms, 27, mkChar("dim_lambda_prod_2"));
  SET_STRING_ELT(nms, 28, mkChar("dim_N"));
  SET_STRING_ELT(nms, 29, mkChar("dim_n_E_I"));
  SET_STRING_ELT(nms, 30, mkChar("dim_n_I_D"));
  SET_STRING_ELT(nms, 31, mkChar("dim_n_I_out"));
  SET_STRING_ELT(nms, 32, mkChar("dim_n_I_R"));
  SET_STRING_ELT(nms, 33, mkChar("dim_n_S_E"));
  SET_STRING_ELT(nms, 34, mkChar("dim_n_S_out"));
  SET_STRING_ELT(nms, 35, mkChar("dim_n_S_V"));
  SET_STRING_ELT(nms, 36, mkChar("dim_p_S_out"));
  SET_STRING_ELT(nms, 37, mkChar("dim_p_S_V"));
  SET_STRING_ELT(nms, 38, mkChar("dim_R"));
  SET_STRING_ELT(nms, 39, mkChar("dim_rate_S_out"));
  SET_STRING_ELT(nms, 40, mkChar("dim_rate_S_V"));
  SET_STRING_ELT(nms, 41, mkChar("dim_response_vacc_coverage"));
  SET_STRING_ELT(nms, 42, mkChar("dim_S"));
  SET_STRING_ELT(nms, 43, mkChar("dim_status"));
  SET_STRING_ELT(nms, 44, mkChar("dim_V"));
  SET_STRING_ELT(nms, 45, mkChar("gamma"));
  SET_STRING_ELT(nms, 46, mkChar("ini_D"));
  SET_STRING_ELT(nms, 47, mkChar("ini_E"));
  SET_STRING_ELT(nms, 48, mkChar("ini_I"));
  SET_STRING_ELT(nms, 49, mkChar("ini_R"));
  SET_STRING_ELT(nms, 50, mkChar("ini_S"));
  SET_STRING_ELT(nms, 51, mkChar("ini_V"));
  SET_STRING_ELT(nms, 52, mkChar("initial_D"));
  SET_STRING_ELT(nms, 53, mkChar("initial_E"));
  SET_STRING_ELT(nms, 54, mkChar("initial_I"));
  SET_STRING_ELT(nms, 55, mkChar("initial_R"));
  SET_STRING_ELT(nms, 56, mkChar("initial_S"));
  SET_STRING_ELT(nms, 57, mkChar("initial_V"));
  SET_STRING_ELT(nms, 58, mkChar("interv_delay"));
  SET_STRING_ELT(nms, 59, mkChar("interv_efficacy"));
  SET_STRING_ELT(nms, 60, mkChar("interv_release"));
  SET_STRING_ELT(nms, 61, mkChar("interv_vacc_coverage"));
  SET_STRING_ELT(nms, 62, mkChar("interv_vacc_type"));
  SET_STRING_ELT(nms, 63, mkChar("lambda"));
  SET_STRING_ELT(nms, 64, mkChar("lambda_prod"));
  SET_STRING_ELT(nms, 65, mkChar("mu"));
  SET_STRING_ELT(nms, 66, mkChar("N"));
  SET_STRING_ELT(nms, 67, mkChar("n_E_I"));
  SET_STRING_ELT(nms, 68, mkChar("n_I_D"));
  SET_STRING_ELT(nms, 69, mkChar("n_I_out"));
  SET_STRING_ELT(nms, 70, mkChar("n_I_R"));
  SET_STRING_ELT(nms, 71, mkChar("n_populations"));
  SET_STRING_ELT(nms, 72, mkChar("n_S_E"));
  SET_STRING_ELT(nms, 73, mkChar("n_S_out"));
  SET_STRING_ELT(nms, 74, mkChar("n_S_V"));
  SET_STRING_ELT(nms, 75, mkChar("offset_variable_D"));
  SET_STRING_ELT(nms, 76, mkChar("offset_variable_I"));
  SET_STRING_ELT(nms, 77, mkChar("offset_variable_R"));
  SET_STRING_ELT(nms, 78, mkChar("offset_variable_V"));
  SET_STRING_ELT(nms, 79, mkChar("p_S_out"));
  SET_STRING_ELT(nms, 80, mkChar("p_S_V"));
  SET_STRING_ELT(nms, 81, mkChar("rate_S_out"));
  SET_STRING_ELT(nms, 82, mkChar("rate_S_V"));
  SET_STRING_ELT(nms, 83, mkChar("response_vacc_coverage"));
  SET_STRING_ELT(nms, 84, mkChar("sigma"));
  SET_STRING_ELT(nms, 85, mkChar("status"));
  SET_STRING_ELT(nms, 86, mkChar("target_size"));
  SET_STRING_ELT(nms, 87, mkChar("vacc_coverage"));
  SET_STRING_ELT(nms, 88, mkChar("vacc_efficacy"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(36);
  return contents;
}
SEXP seirdv_set_user(SEXP internal_p, SEXP user) {
  seirdv_internal *internal = seirdv_get_internal(internal_p, 1);
  internal->beta = user_get_scalar_double(user, "beta", internal->beta, NA_REAL, NA_REAL);
  internal->gamma = user_get_scalar_double(user, "gamma", internal->gamma, NA_REAL, NA_REAL);
  internal->interv_delay = user_get_scalar_double(user, "interv_delay", internal->interv_delay, NA_REAL, NA_REAL);
  internal->interv_efficacy = user_get_scalar_double(user, "interv_efficacy", internal->interv_efficacy, NA_REAL, NA_REAL);
  internal->interv_release = user_get_scalar_double(user, "interv_release", internal->interv_release, NA_REAL, NA_REAL);
  internal->interv_vacc_coverage = user_get_scalar_double(user, "interv_vacc_coverage", internal->interv_vacc_coverage, NA_REAL, NA_REAL);
  internal->interv_vacc_type = user_get_scalar_double(user, "interv_vacc_type", internal->interv_vacc_type, NA_REAL, NA_REAL);
  internal->mu = user_get_scalar_double(user, "mu", internal->mu, NA_REAL, NA_REAL);
  internal->n_populations = user_get_scalar_int(user, "n_populations", internal->n_populations, NA_REAL, NA_REAL);
  internal->sigma = user_get_scalar_double(user, "sigma", internal->sigma, NA_REAL, NA_REAL);
  internal->target_size = user_get_scalar_double(user, "target_size", internal->target_size, NA_REAL, NA_REAL);
  internal->vacc_coverage = user_get_scalar_double(user, "vacc_coverage", internal->vacc_coverage, NA_REAL, NA_REAL);
  internal->vacc_efficacy = user_get_scalar_double(user, "vacc_efficacy", internal->vacc_efficacy, NA_REAL, NA_REAL);
  internal->dim_active = internal->n_populations;
  internal->dim_beta_vec = internal->n_populations;
  internal->dim_coverage_vec = internal->n_populations;
  internal->dim_D = internal->n_populations;
  internal->dim_days_active = internal->n_populations;
  internal->dim_days_no_case = internal->n_populations;
  internal->dim_delta_1 = internal->n_populations;
  internal->dim_delta_2 = internal->n_populations;
  internal->dim_E = internal->n_populations;
  internal->dim_I = internal->n_populations;
  internal->dim_ini_D = internal->n_populations;
  internal->dim_ini_E = internal->n_populations;
  internal->dim_ini_I = internal->n_populations;
  internal->dim_ini_R = internal->n_populations;
  internal->dim_ini_S = internal->n_populations;
  internal->dim_ini_V = internal->n_populations;
  internal->dim_lambda = internal->n_populations;
  internal->dim_lambda_prod_1 = internal->n_populations;
  internal->dim_lambda_prod_2 = internal->n_populations;
  internal->dim_N = internal->n_populations;
  internal->dim_n_E_I = internal->n_populations;
  internal->dim_n_I_D = internal->n_populations;
  internal->dim_n_I_out = internal->n_populations;
  internal->dim_n_I_R = internal->n_populations;
  internal->dim_n_S_E = internal->n_populations;
  internal->dim_n_S_out = internal->n_populations;
  internal->dim_n_S_V = internal->n_populations;
  internal->dim_p_S_out = internal->n_populations;
  internal->dim_p_S_V = internal->n_populations;
  internal->dim_R = internal->n_populations;
  internal->dim_rate_S_out = internal->n_populations;
  internal->dim_rate_S_V = internal->n_populations;
  internal->dim_response_vacc_coverage = internal->n_populations;
  internal->dim_S = internal->n_populations;
  internal->dim_status = internal->n_populations;
  internal->dim_V = internal->n_populations;
  R_Free(internal->active);
  internal->active = (double*) R_Calloc(internal->dim_active, double);
  R_Free(internal->beta_vec);
  internal->beta_vec = (double*) R_Calloc(internal->dim_beta_vec, double);
  R_Free(internal->coverage_vec);
  internal->coverage_vec = (double*) R_Calloc(internal->dim_coverage_vec, double);
  R_Free(internal->days_active);
  internal->days_active = (double*) R_Calloc(internal->dim_days_active, double);
  R_Free(internal->days_no_case);
  internal->days_no_case = (double*) R_Calloc(internal->dim_days_no_case, double);
  R_Free(internal->initial_D);
  internal->initial_D = (double*) R_Calloc(internal->dim_D, double);
  R_Free(internal->initial_E);
  internal->initial_E = (double*) R_Calloc(internal->dim_E, double);
  R_Free(internal->initial_I);
  internal->initial_I = (double*) R_Calloc(internal->dim_I, double);
  R_Free(internal->initial_R);
  internal->initial_R = (double*) R_Calloc(internal->dim_R, double);
  R_Free(internal->initial_S);
  internal->initial_S = (double*) R_Calloc(internal->dim_S, double);
  R_Free(internal->initial_V);
  internal->initial_V = (double*) R_Calloc(internal->dim_V, double);
  R_Free(internal->lambda);
  internal->lambda = (double*) R_Calloc(internal->dim_lambda, double);
  R_Free(internal->N);
  internal->N = (double*) R_Calloc(internal->dim_N, double);
  R_Free(internal->n_E_I);
  internal->n_E_I = (double*) R_Calloc(internal->dim_n_E_I, double);
  R_Free(internal->n_I_D);
  internal->n_I_D = (double*) R_Calloc(internal->dim_n_I_D, double);
  R_Free(internal->n_I_out);
  internal->n_I_out = (double*) R_Calloc(internal->dim_n_I_out, double);
  R_Free(internal->n_I_R);
  internal->n_I_R = (double*) R_Calloc(internal->dim_n_I_R, double);
  R_Free(internal->n_S_E);
  internal->n_S_E = (double*) R_Calloc(internal->dim_n_S_E, double);
  R_Free(internal->n_S_out);
  internal->n_S_out = (double*) R_Calloc(internal->dim_n_S_out, double);
  R_Free(internal->n_S_V);
  internal->n_S_V = (double*) R_Calloc(internal->dim_n_S_V, double);
  R_Free(internal->p_S_out);
  internal->p_S_out = (double*) R_Calloc(internal->dim_p_S_out, double);
  R_Free(internal->p_S_V);
  internal->p_S_V = (double*) R_Calloc(internal->dim_p_S_V, double);
  R_Free(internal->rate_S_out);
  internal->rate_S_out = (double*) R_Calloc(internal->dim_rate_S_out, double);
  R_Free(internal->rate_S_V);
  internal->rate_S_V = (double*) R_Calloc(internal->dim_rate_S_V, double);
  R_Free(internal->response_vacc_coverage);
  internal->response_vacc_coverage = (double*) R_Calloc(internal->dim_response_vacc_coverage, double);
  R_Free(internal->status);
  internal->status = (double*) R_Calloc(internal->dim_status, double);
  internal->dim_delta = internal->dim_delta_1 * internal->dim_delta_2;
  internal->dim_lambda_prod = internal->dim_lambda_prod_1 * internal->dim_lambda_prod_2;
  internal->ini_D = (double*) user_get_array(user, false, internal->ini_D, "ini_D", NA_REAL, NA_REAL, 1, internal->dim_ini_D);
  internal->ini_E = (double*) user_get_array(user, false, internal->ini_E, "ini_E", NA_REAL, NA_REAL, 1, internal->dim_ini_E);
  internal->ini_I = (double*) user_get_array(user, false, internal->ini_I, "ini_I", NA_REAL, NA_REAL, 1, internal->dim_ini_I);
  internal->ini_R = (double*) user_get_array(user, false, internal->ini_R, "ini_R", NA_REAL, NA_REAL, 1, internal->dim_ini_R);
  internal->ini_S = (double*) user_get_array(user, false, internal->ini_S, "ini_S", NA_REAL, NA_REAL, 1, internal->dim_ini_S);
  internal->ini_V = (double*) user_get_array(user, false, internal->ini_V, "ini_V", NA_REAL, NA_REAL, 1, internal->dim_ini_V);
  internal->offset_variable_D = internal->dim_E + internal->dim_I + internal->dim_R + internal->dim_S;
  internal->offset_variable_I = internal->dim_E + internal->dim_S;
  internal->offset_variable_R = internal->dim_E + internal->dim_I + internal->dim_S;
  internal->offset_variable_V = internal->dim_D + internal->dim_E + internal->dim_I + internal->dim_R + internal->dim_S;
  R_Free(internal->lambda_prod);
  internal->lambda_prod = (double*) R_Calloc(internal->dim_lambda_prod, double);
  internal->delta = (double*) user_get_array(user, false, internal->delta, "delta", NA_REAL, NA_REAL, 2, internal->dim_delta_1, internal->dim_delta_2);
  for (int i = 1; i <= internal->dim_D; ++i) {
    internal->initial_D[i - 1] = internal->ini_D[i - 1];
  }
  for (int i = 1; i <= internal->dim_E; ++i) {
    internal->initial_E[i - 1] = internal->ini_E[i - 1];
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    internal->initial_I[i - 1] = internal->ini_I[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    internal->initial_R[i - 1] = internal->ini_R[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    internal->initial_S[i - 1] = internal->ini_S[i - 1];
  }
  for (int i = 1; i <= internal->dim_V; ++i) {
    internal->initial_V[i - 1] = internal->ini_V[i - 1];
  }
  return R_NilValue;
}
SEXP seirdv_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr) {
  return R_NilValue;
}
SEXP seirdv_metadata(SEXP internal_p) {
  seirdv_internal *internal = seirdv_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 6));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 6));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(variable_length, 1, ScalarInteger(internal->dim_E));
  SET_VECTOR_ELT(variable_length, 2, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(variable_length, 3, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(variable_length, 4, ScalarInteger(internal->dim_D));
  SET_VECTOR_ELT(variable_length, 5, ScalarInteger(internal->dim_V));
  SET_STRING_ELT(variable_names, 0, mkChar("S"));
  SET_STRING_ELT(variable_names, 1, mkChar("E"));
  SET_STRING_ELT(variable_names, 2, mkChar("I"));
  SET_STRING_ELT(variable_names, 3, mkChar("R"));
  SET_STRING_ELT(variable_names, 4, mkChar("D"));
  SET_STRING_ELT(variable_names, 5, mkChar("V"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SEXP output_length = PROTECT(allocVector(VECSXP, 1));
  SEXP output_names = PROTECT(allocVector(STRSXP, 1));
  setAttrib(output_length, R_NamesSymbol, output_names);
  SET_VECTOR_ELT(output_length, 0, ScalarInteger(internal->dim_status));
  SET_STRING_ELT(output_names, 0, mkChar("status"));
  SET_VECTOR_ELT(ret, 1, output_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(internal->dim_status));
  UNPROTECT(2);
  return ret;
}
SEXP seirdv_initial_conditions(SEXP internal_p, SEXP step_ptr) {
  seirdv_internal *internal = seirdv_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_D + internal->dim_E + internal->dim_I + internal->dim_R + internal->dim_S + internal->dim_V));
  double * state = REAL(r_state);
  memcpy(state + 0, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->dim_S, internal->initial_E, internal->dim_E * sizeof(double));
  memcpy(state + internal->offset_variable_I, internal->initial_I, internal->dim_I * sizeof(double));
  memcpy(state + internal->offset_variable_R, internal->initial_R, internal->dim_R * sizeof(double));
  memcpy(state + internal->offset_variable_D, internal->initial_D, internal->dim_D * sizeof(double));
  memcpy(state + internal->offset_variable_V, internal->initial_V, internal->dim_V * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void seirdv_rhs(seirdv_internal* internal, size_t step, double * state, double * state_next, double * output) {
  double * S = state + 0;
  double * E = state + internal->dim_S;
  double * I = state + internal->offset_variable_I;
  double * R = state + internal->offset_variable_R;
  double * D = state + internal->offset_variable_D;
  double * V = state + internal->offset_variable_V;
  for (int i = 1; i <= internal->dim_days_no_case; ++i) {
    internal->days_no_case[i - 1] = ((int) (step) == 1 ? 0 : internal->days_no_case[i - 1]);
  }
  for (int i = 1; i <= internal->dim_days_no_case; ++i) {
    internal->days_no_case[i - 1] = (I[i - 1] == 0 ? internal->days_no_case[i - 1] + 1 : 0);
  }
  for (int i = 1; i <= internal->dim_N; ++i) {
    internal->N[i - 1] = S[i - 1] + E[i - 1] + I[i - 1] + R[i - 1] + V[i - 1];
  }
  for (int i = 1; i <= internal->dim_n_E_I; ++i) {
    internal->n_E_I[i - 1] = (E[i - 1] > 0 ? Rf_rbinom(round(E[i - 1]), 1 - exp(-(internal->sigma))) : 0);
  }
  for (int i = 1; i <= internal->dim_n_I_out; ++i) {
    internal->n_I_out[i - 1] = (I[i - 1] > 0 ? Rf_rbinom(round(I[i - 1]), 1 - exp(-(internal->gamma))) : 0);
  }
  for (int i = 1; i <= internal->dim_active; ++i) {
    internal->active[i - 1] = ((int) (step) == 1 ? 0 : internal->active[i - 1]);
  }
  for (int i = 1; i <= internal->dim_active; ++i) {
    internal->active[i - 1] = (I[i - 1] > 0 ? 1 : internal->active[i - 1]);
  }
  for (int i = 1; i <= internal->dim_active; ++i) {
    internal->active[i - 1] = (internal->days_no_case[i - 1] > internal->interv_release ? 0 : internal->active[i - 1]);
  }
  for (int i = 1; i <= internal->dim_n_I_R; ++i) {
    internal->n_I_R[i - 1] = (internal->n_I_out[i - 1] > 0 ? Rf_rbinom(round(internal->n_I_out[i - 1]), 1 - internal->mu) : 0);
  }
  for (int i = 1; i <= internal->dim_days_active; ++i) {
    internal->days_active[i - 1] = ((int) (step) == 1 ? 0 : internal->days_active[i - 1]);
  }
  for (int i = 1; i <= internal->dim_days_active; ++i) {
    internal->days_active[i - 1] = (internal->active[i - 1] == 1 ? internal->days_active[i - 1] + 1 : 0);
  }
  for (int i = 1; i <= internal->dim_n_I_D; ++i) {
    internal->n_I_D[i - 1] = internal->n_I_out[i - 1] - internal->n_I_R[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    state_next[internal->offset_variable_R + i - 1] = R[i - 1] + internal->n_I_R[i - 1];
  }
  for (int i = 1; i <= internal->dim_status; ++i) {
    internal->status[i - 1] = ((int) (step) == 1 ? 0 : internal->status[i - 1]);
  }
  for (int i = 1; i <= internal->dim_status; ++i) {
    internal->status[i - 1] = (internal->days_active[i - 1] > internal->interv_delay ? 1 : internal->status[i - 1]);
  }
  for (int i = 1; i <= internal->dim_status; ++i) {
    internal->status[i - 1] = (internal->days_no_case[i - 1] > internal->interv_release ? 0 : internal->status[i - 1]);
  }
  for (int i = 1; i <= internal->dim_D; ++i) {
    state_next[internal->offset_variable_D + i - 1] = D[i - 1] + internal->n_I_D[i - 1];
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    state_next[internal->offset_variable_I + i - 1] = I[i - 1] + internal->n_E_I[i - 1] - internal->n_I_R[i - 1] - internal->n_I_D[i - 1];
  }
  for (int i = 1; i <= internal->dim_beta_vec; ++i) {
    internal->beta_vec[i - 1] = (internal->status[i - 1] == 1 ? internal->beta * (1 - internal->interv_efficacy) : internal->beta);
  }
  for (int i = 1; i <= internal->dim_response_vacc_coverage; ++i) {
    internal->response_vacc_coverage[i - 1] = (internal->status[i - 1] == 1 && (int) (internal->interv_vacc_type) == 1 ? internal->interv_vacc_coverage : (internal->status[i - 1] == 1 && (int) (internal->interv_vacc_type) == 2 && S[i - 1] > 0 ? internal->target_size * I[i - 1] / (double) S[i - 1] : 0));
  }
  for (int i = 1; i <= internal->dim_coverage_vec; ++i) {
    internal->coverage_vec[i - 1] = (internal->status[i - 1] == 1 ? internal->vacc_coverage + internal->response_vacc_coverage[i - 1] : internal->vacc_coverage);
  }
  for (int i = 1; i <= internal->dim_coverage_vec; ++i) {
    internal->coverage_vec[i - 1] = (internal->coverage_vec[i - 1] > 1 ? 1 : internal->coverage_vec[i - 1]);
  }
  for (int i = 1; i <= internal->dim_lambda_prod_1; ++i) {
    for (int j = 1; j <= internal->dim_lambda_prod_2; ++j) {
      internal->lambda_prod[i - 1 + internal->dim_lambda_prod_1 * (j - 1)] = internal->beta_vec[i - 1] * internal->delta[internal->dim_delta_1 * (j - 1) + i - 1] * I[i - 1] / (double) internal->N[i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_lambda; ++i) {
    internal->lambda[i - 1] = odin_sum2(internal->lambda_prod, 0, internal->dim_lambda_prod_1, i - 1, i, internal->dim_lambda_prod_1);
  }
  for (int i = 1; i <= internal->dim_p_S_V; ++i) {
    internal->p_S_V[i - 1] = internal->coverage_vec[i - 1] * internal->vacc_efficacy;
  }
  for (int i = 1; i <= internal->dim_p_S_V; ++i) {
    internal->p_S_V[i - 1] = (internal->p_S_V[i - 1] > 1 ? 1 : internal->p_S_V[i - 1]);
  }
  for (int i = 1; i <= internal->dim_rate_S_V; ++i) {
    internal->rate_S_V[i - 1] = -(log(1 - internal->p_S_V[i - 1]));
  }
  for (int i = 1; i <= internal->dim_rate_S_out; ++i) {
    internal->rate_S_out[i - 1] = internal->lambda[i - 1] + internal->rate_S_V[i - 1];
  }
  for (int i = 1; i <= internal->dim_p_S_out; ++i) {
    internal->p_S_out[i - 1] = 1 - exp(-(internal->rate_S_out[i - 1]));
  }
  for (int i = 1; i <= internal->dim_n_S_out; ++i) {
    internal->n_S_out[i - 1] = (S[i - 1] > 0 ? Rf_rbinom(round(S[i - 1]), internal->p_S_out[i - 1]) : 0);
  }
  for (int i = 1; i <= internal->dim_n_S_E; ++i) {
    internal->n_S_E[i - 1] = (internal->n_S_out[i - 1] > 0 ? Rf_rbinom(round(internal->n_S_out[i - 1]), internal->lambda[i - 1] / (double) internal->rate_S_out[i - 1]) : 0);
  }
  for (int i = 1; i <= internal->dim_n_S_V; ++i) {
    internal->n_S_V[i - 1] = internal->n_S_out[i - 1] - internal->n_S_E[i - 1];
  }
  for (int i = 1; i <= internal->dim_E; ++i) {
    state_next[internal->dim_S + i - 1] = E[i - 1] + internal->n_S_E[i - 1] - internal->n_E_I[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    state_next[0 + i - 1] = S[i - 1] - internal->n_S_E[i - 1] - internal->n_S_V[i - 1];
  }
  for (int i = 1; i <= internal->dim_V; ++i) {
    state_next[internal->offset_variable_V + i - 1] = V[i - 1] + internal->n_S_V[i - 1];
  }
  memcpy(output + 0, internal->status, internal->dim_status * sizeof(double));
}
void seirdv_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal) {
  seirdv_rhs((seirdv_internal*)internal, step, state, state_next, output);
}
SEXP seirdv_rhs_r(SEXP internal_p, SEXP step, SEXP state) {
  SEXP state_next = PROTECT(allocVector(REALSXP, LENGTH(state)));
  seirdv_internal *internal = seirdv_get_internal(internal_p, 1);
  SEXP output_ptr = PROTECT(allocVector(REALSXP, internal->dim_status));
  setAttrib(state_next, install("output"), output_ptr);
  UNPROTECT(1);
  double *output = REAL(output_ptr);
  GetRNGstate();
  seirdv_rhs(internal, scalar_int(step, "step"), REAL(state), REAL(state_next), output);
  PutRNGstate();
  UNPROTECT(1);
  return state_next;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
void odin_set_dim(SEXP target, int rank, ...) {
  SEXP r_dim = PROTECT(allocVector(INTSXP, rank));
  int *dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t)rank; ++i) {
    dim[i] = va_arg(ap, int);
  }
  va_end(ap);

  setAttrib(target, R_DimSymbol, r_dim);
  UNPROTECT(1);
}
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  dest_dim[0] = LENGTH(el);
  if (rank > 1) {
    SEXP r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
    int *dim = INTEGER(r_dim);

    for (size_t i = 0; i < (size_t) rank; ++i) {
      dest_dim[i + 1] = dim[i];
    }

    UNPROTECT(1);
  }

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  int len = LENGTH(el);
  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  SEXP r_dim;
  int *dim;

  size_t len = LENGTH(el);
  if (rank == 1) {
    r_dim = PROTECT(ScalarInteger(len));
  } else {
    r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
  }
  dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t) rank; ++i) {
    int dim_expected = va_arg(ap, int);
    if (dim[i] != dim_expected) {
      va_end(ap); // avoid a leak
      if (rank == 1) {
        Rf_error("Expected length %d value for '%s'", dim_expected, name);
      } else {
        Rf_error("Incorrect size of dimension %d of '%s' (expected %d)",
                 (int)i + 1, name, dim_expected);
      }
    }
  }
  va_end(ap);
  UNPROTECT(1);

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max) {
  size_t len = (size_t) length(el);
  if (is_integer) {
    if (TYPEOF(el) == INTSXP) {
      user_check_values_int(INTEGER(el), len, min, max, name);
    } else if (TYPEOF(el) == REALSXP) {
      el = PROTECT(coerceVector(el, INTSXP));
      user_check_values_int(INTEGER(el), len, min, max, name);
      UNPROTECT(1);
    } else {
      Rf_error("Expected a integer value for '%s'", name);
    }
  } else {
    if (TYPEOF(el) == INTSXP) {
      el = PROTECT(coerceVector(el, REALSXP));
      user_check_values_double(REAL(el), len, min, max, name);
      UNPROTECT(1);
    } else if (TYPEOF(el) == REALSXP) {
      user_check_values_double(REAL(el), len, min, max, name);
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  return el;
}
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required) {
  SEXP el = user_list_element(user, name);
  if (el == R_NilValue) {
    if (required) {
      Rf_error("Expected a value for '%s'", name);
    }
  } else {
    if (rank == 1) {
      if (isArray(el)) {
        Rf_error("Expected a numeric vector for '%s'", name);
      }
    } else {
      SEXP r_dim = getAttrib(el, R_DimSymbol);
      if (r_dim == R_NilValue || LENGTH(r_dim) != rank) {
        if (rank == 2) {
          Rf_error("Expected a numeric matrix for '%s'", name);
        } else {
          Rf_error("Expected a numeric array of rank %d for '%s'", rank, name);
        }
      }
    }
  }
  return el;
}
int scalar_int(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  int ret = 0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    double rx = REAL(x)[0];
    ret = rx;
    if (fabs(rx - ret) > sqrt(DBL_EPSILON)) {
      Rf_error("Expected a integer-like for '%s'", name);
    }
  } else {
    Rf_error("Expected an integer value for '%s'", name);
  }
  return ret;
}
double odin_sum1(double *x, size_t from, size_t to) {
  double tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1) {
  double tot = 0.0;
  for (int j = from_j; j < to_j; ++j) {
    int jj = j * dim_x_1;
    for (int i = from_i; i < to_i; ++i) {
      tot += x[i + jj];
    }
  }
  return tot;
}
