# Generated by Django 4.2.4 on 2026-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pami', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pamidata',
            old_name='metadata',
            new_name='additional_data',
        ),
        migrations.AddField(
            model_name='pamidata',
            name='risk_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
