# Generated by Django 4.2.4 on 2026-03-10 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentinel', '0002_add_duplicate_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('trust_level', models.CharField(choices=[('verified', 'Verified'), ('corroborated', 'Corroborated'), ('unverified', 'Unverified'), ('unconfirmed', 'Unconfirmed')], default='unconfirmed', max_length=20)),
                ('source_tier_weight', models.FloatField(default=0.0)),
                ('corroboration_count', models.IntegerField(default=0)),
                ('disease_match_confidence', models.IntegerField(default=0)),
                ('recency_factor', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust', to='sentinel.signal')),
            ],
            options={
                'db_table': 'hdis_pro_trustscore',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_type', models.CharField(default='daily', max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('country_filter', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(default='system', max_length=100)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_briefings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hdis_pro_briefing',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('trigger_reason', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('signal_strength', models.IntegerField(default=1)),
                ('multi_source_validated', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdis_alerts', to='sentinel.signal')),
            ],
            options={
                'db_table': 'hdis_pro_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['risk_level'], name='hdis_pro_al_risk_le_ee05a8_idx'), models.Index(fields=['-created_at'], name='hdis_pro_al_created_374ca7_idx')],
            },
        ),
    ]
