# Generated by Django 4.2.4 on 2026-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('rest_api', 'REST API'), ('web_scrape', 'Web Scraper')], max_length=20)),
                ('url', models.URLField(help_text='RSS feed URL, API endpoint, or target URL')),
                ('auth_header', models.CharField(blank=True, help_text="Optional auth header value (e.g., 'Bearer xxx' or API key)", max_length=500)),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Extra query params or config (JSON). E.g., ACLED filters.')),
                ('default_pillar', models.CharField(choices=[('outbreak', 'Disease Outbreak & Surveillance'), ('policy', 'Health Policy & Governance'), ('funding', 'Health Funding & Aid'), ('vaccine', 'Vaccine Diplomacy & Access'), ('conflict', 'Conflict & Health Systems'), ('climate', 'Climate & Health'), ('agreement', 'Health Agreements & Treaties'), ('workforce', 'Health Workforce & Capacity'), ('uhc', 'Universal Health Coverage')], default='outbreak', help_text='Default pillar if keyword classifier returns no match', max_length=20)),
                ('source_tier', models.IntegerField(choices=[(1, 'Tier 1 — Official'), (2, 'Tier 2 — Verified Media'), (3, 'Tier 3 — Unverified')], default=3, help_text='Trust tier for the trust engine')),
                ('keyword_include', models.JSONField(blank=True, default=list, help_text='Only ingest items matching ANY of these keywords (empty = accept all)')),
                ('keyword_exclude', models.JSONField(blank=True, default=list, help_text='Reject items matching ANY of these keywords')),
                ('require_africa', models.BooleanField(default=True, help_text='Only ingest signals mentioning an African country')),
                ('is_active', models.BooleanField(default=True)),
                ('poll_interval_minutes', models.IntegerField(default=30, help_text='How often to poll this source (minutes)')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('total_ingested', models.IntegerField(default=0)),
                ('total_rejected', models.IntegerField(default=0)),
                ('total_duplicates', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hdis_pro_sourceconfig',
                'ordering': ['name'],
            },
        ),
    ]
