# Generated by Django 4.2.4 on 2026-03-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdis', '0002_sourceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='confidence_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='briefing',
            name='country_iso',
            field=models.CharField(blank=True, default='', help_text='ISO3 code for country-focus briefings', max_length=3),
        ),
        migrations.AddField(
            model_name='briefing',
            name='generation_time_ms',
            field=models.IntegerField(default=0, help_text='Pipeline exec ms'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='llm_model',
            field=models.CharField(blank=True, default='', help_text='LLM model used for generation', max_length=100),
        ),
        migrations.AddField(
            model_name='briefing',
            name='pipeline_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw output from each pipeline stage for audit'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='scope',
            field=models.CharField(choices=[('daily_global', 'Daily Global (All AFRO)'), ('country_focus', 'Country Focus'), ('crisis_alert', 'Crisis Alert')], default='daily_global', max_length=20),
        ),
        migrations.AddField(
            model_name='briefing',
            name='signal_count',
            field=models.IntegerField(default=0, help_text='Signals analyzed'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='source_count',
            field=models.IntegerField(default=0, help_text='Distinct sources used'),
        ),
    ]
