# Generated by Django 4.2.4 on 2026-03-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdis', '0003_briefing_engine_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='daily_global', max_length=30)),
                ('country_iso', models.CharField(blank=True, default='', max_length=3)),
                ('hours_back', models.IntegerField(default=48)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('gathering', 'Gathering Signals'), ('analyzing', 'LLM Analysis'), ('verifying', 'Verification'), ('composing', 'Composing Briefing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(default='system', max_length=100)),
                ('briefing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='hdis.briefing')),
            ],
            options={
                'db_table': 'hdis_pro_generation_job',
                'ordering': ['-started_at'],
            },
        ),
    ]
