# Generated by Django 4.2.4 on 2026-04-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_add_tenant_model_and_user_fk'),
        ('hdis', '0004_add_briefing_generation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from signal.tenant for direct RLS.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdis_alerts', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant for RLS. Populated from country_iso; global briefings → AFR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefings', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='briefinggenerationjob',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant for RLS. Populated from country_iso; global jobs → AFR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='trustscore',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from signal.tenant for direct RLS.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to='account.tenant'),
        ),
    ]
