
export interface ChatMessage {
    role: 'user' | 'assistant' | 'system';
    content: string;
}

export const generateLpiPlanWithAzure = async (scenario: any) => {
    await new Promise(resolve => setTimeout(resolve, 1500));
    return {
        result: {
            changeSummary: "This is a simulated plan generated by the mock Azure service.",
            riskAssessment: {
                riskLevel: "High",
                reproductionNumberR0: 2.5,
                projectedSpreadRadiusKm: 50
            },
            logisticsConstraints: ["Road access limited", "Fuel shortage"],
            planningAssumptions: ["Population density remains constant", "No new outbreaks"],
            budgetAnalysis: {
                totalCostUSD: 50000,
                breakdown: [
                    { pillar: "Logistics", estimatedCostUSD: 20000 },
                    { pillar: "Personnel", estimatedCostUSD: 15000 },
                    { pillar: "Supplies", estimatedCostUSD: 15000 }
                ]
            },
            logisticsPlan: {
                totalWeightKg: 1500,
                transportMode: "Truck",
                estimatedLeadTimeDays: 5
            },
            executiveSummary: "Summary of the logistics plan...",
            keyInterventions: ["Deploy mobile clinics", "Stockpile vaccines"],
            commodityStockpile: [
                {
                    category: "Medical Supplies",
                    items: [
                        { commodityName: "Gloves", quantity: 1000, unit: "pairs" },
                        { commodityName: "Masks", quantity: 5000, unit: "pcs" }
                    ]
                }
            ]
        },
        messages: []
    };
};

export const refineLpiPlanWithAzure = async (scenario: any, message: string, history: any[]) => {
    // Mock implementation
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
        result: {
            changeSummary: "Plan updated based on your feedback (Mock).",
            // ... include other necessary mock data structure similar to above if needed or partial updates
        },
        messages: []
    };
};
