# Generated by Django 4.2.4 on 2026-02-08 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('vhf', 'Viral Hemorrhagic Fever'), ('respiratory', 'Respiratory'), ('enteric', 'Enteric'), ('vector_borne', 'Vector Borne'), ('zoonotic', 'Zoonotic'), ('vaccine_preventable', 'Vaccine Preventable'), ('environmental', 'Environmental'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('default_priority', models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Medium'), ('P4', 'Low')], default='P3', max_length=2)),
                ('keywords_en', models.JSONField(blank=True, default=list)),
                ('keywords_fr', models.JSONField(blank=True, default=list)),
                ('keywords_pt', models.JSONField(blank=True, default=list)),
                ('keywords_ar', models.JSONField(blank=True, default=list)),
                ('keywords_sw', models.JSONField(blank=True, default=list)),
                ('keywords_ha', models.JSONField(blank=True, default=list)),
                ('keywords_yo', models.JSONField(blank=True, default=list)),
                ('keywords_am', models.JSONField(blank=True, default=list)),
                ('symptoms_cluster', models.JSONField(blank=True, default=list)),
                ('endemic_regions', models.JSONField(blank=True, default=list)),
                ('case_fatality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incubation_days_min', models.IntegerField(blank=True, null=True)),
                ('incubation_days_max', models.IntegerField(blank=True, null=True)),
                ('transmission_routes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['disease_name'],
            },
        ),
        migrations.CreateModel(
            name='SourceCredibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200, unique=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=50)),
                ('tier', models.IntegerField(choices=[(1, 'Official (WHO, Ministry)'), (2, 'Verified Media'), (3, 'Unverified')], default=3)),
                ('credibility_score', models.IntegerField(default=50)),
                ('total_signals', models.IntegerField(default=0)),
                ('validated_signals', models.IntegerField(default=0)),
                ('false_positive_count', models.IntegerField(default=0)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Source Credibilities',
                'ordering': ['-credibility_score'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(default='disease', max_length=50)),
                ('disease_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_category', models.CharField(blank=True, choices=[('vhf', 'Viral Hemorrhagic Fever'), ('respiratory', 'Respiratory'), ('enteric', 'Enteric'), ('vector_borne', 'Vector Borne'), ('zoonotic', 'Zoonotic'), ('vaccine_preventable', 'Vaccine Preventable'), ('environmental', 'Environmental'), ('unknown', 'Unknown')], max_length=50, null=True)),
                ('location_country', models.CharField(max_length=100)),
                ('location_country_iso', models.CharField(blank=True, max_length=3, null=True)),
                ('location_admin1', models.CharField(blank=True, max_length=100, null=True)),
                ('location_admin2', models.CharField(blank=True, max_length=100, null=True)),
                ('location_locality', models.CharField(blank=True, max_length=200, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('original_text', models.TextField()),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('original_script', models.CharField(blank=True, max_length=20, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('translation_confidence', models.IntegerField(blank=True, null=True)),
                ('lingua_fidelity_score', models.IntegerField(blank=True, null=True)),
                ('source_tier', models.IntegerField(choices=[(1, 'Official (WHO, Ministry)'), (2, 'Verified Media'), (3, 'Unverified')], default=3)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Medium'), ('P4', 'Low')], default='P4', max_length=2)),
                ('confidence_score', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('validated', 'Validated'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('reported_cases', models.IntegerField(blank=True, null=True)),
                ('reported_deaths', models.IntegerField(blank=True, null=True)),
                ('affected_population', models.TextField(blank=True, null=True)),
                ('cross_border_risk', models.BooleanField(default=False)),
                ('seasonal_pattern_match', models.BooleanField(default=False)),
                ('analyst_notes', models.TextField(blank=True, null=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_source', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='sentinel.sourcecredibility')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_signals', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location_country'], name='sentinel_si_locatio_24322a_idx'), models.Index(fields=['priority'], name='sentinel_si_priorit_0bf3f1_idx'), models.Index(fields=['status'], name='sentinel_si_status_50d7b8_idx'), models.Index(fields=['disease_name'], name='sentinel_si_disease_9e855c_idx'), models.Index(fields=['-created_at'], name='sentinel_si_created_1f80a7_idx')],
            },
        ),
    ]
