# Generated by Django 4.2.4 on 2026-02-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='duplicate_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
