# Generated by Django 4.2.4 on 2026-03-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0002_add_duplicate_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='pillar',
            field=models.CharField(db_index=True, default='outbreak', help_text='Primary health diplomacy pillar', max_length=20),
        ),
        migrations.AddField(
            model_name='signal',
            name='secondary_pillars',
            field=models.JSONField(blank=True, default=list, help_text='Additional pillars for cross-pillar signals'),
        ),
    ]
