# Generated by Django 4.2.4 on 2026-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_add_pillar_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='location_country_iso',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
