# Generated by Django 4.2.4 on 2026-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0004_add_country_iso_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasekeyword',
            name='disease_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='disease_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='location_admin1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='location_admin2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='location_country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='location_country_iso',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='location_locality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.TextField(default='disease'),
        ),
    ]
