# Generated by Django 4.2.4 on 2026-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0005_charfield_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='ai_classification',
            field=models.CharField(blank=True, db_index=True, help_text='AI verdict: area_alert, continent_alert, no_alert, uncertain', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='ai_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='ai_notification_scope',
            field=models.CharField(blank=True, help_text='Notification scope: local, continental, worldwide', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='LLM explanation for classification and severity', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='ai_severity',
            field=models.CharField(blank=True, help_text='AI severity: low, moderate, high, critical', max_length=20, null=True),
        ),
    ]
