# Generated by Django 4.2.4 on 2026-04-26 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0007_populate_disease_epi_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Final adjudicated confidence in [0.000, 1.000]', max_digits=4, null=True)),
                ('corroboration_count', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='sentinel.signal')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('perceive', 'Perceive'), ('classify', 'Classify'), ('corroborate', 'Corroborate'), ('review', 'Review'), ('notify', 'Notify'), ('reflect', 'Reflect')], max_length=20)),
                ('agent_name', models.CharField(blank=True, default='', max_length=60)),
                ('input_summary', models.TextField(blank=True, default='')),
                ('output_summary', models.TextField(blank=True, default='')),
                ('reasoning', models.TextField(blank=True, default='')),
                ('citations', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sentinel.agentrun')),
            ],
            options={
                'ordering': ['run', 'step_number'],
                'indexes': [models.Index(fields=['run', 'step_number'], name='sentinel_ag_run_id_cd1145_idx'), models.Index(fields=['-created_at'], name='sentinel_ag_created_d96d8d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_number'), name='agentstep_unique_step_per_run'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['signal', '-started_at'], name='sentinel_ag_signal__85bd28_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-started_at'], name='sentinel_ag_status_a662d5_idx'),
        ),
    ]
