# Generated by Django 4.2.4 on 2026-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0008_agentrun_agentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstep',
            name='kind',
            field=models.CharField(choices=[('perceive', 'Perceive'), ('classify', 'Classify'), ('corroborate', 'Corroborate'), ('debate', 'Debate'), ('review', 'Review'), ('notify', 'Notify'), ('reflect', 'Reflect')], max_length=20),
        ),
    ]
