# Generated by Django 4.2.4 on 2026-04-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0008_add_tenant_fk'),
        ('sentinel', '0009_add_debate_step_kind'),
    ]

    operations = [
    ]
