# Generated by Django 4.2.4 on 2026-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0011_enable_rls_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='source_tier',
            field=models.IntegerField(choices=[(0, 'Ground Truth (Field)'), (1, 'Official (WHO, Ministry)'), (2, 'Verified Media'), (3, 'Unverified')], default=3),
        ),
        migrations.AlterField(
            model_name='sourcecredibility',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Ground Truth (Field)'), (1, 'Official (WHO, Ministry)'), (2, 'Verified Media'), (3, 'Unverified')], default=3),
        ),
    ]
