"""
HDIS Intelligence - Models
Extends sentinel's Signal model with intelligence-layer concepts:
Alert, Briefing, and cached TrustScore.
"""

from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from sentinel.models import Signal

User = get_user_model()


class TrustLevel(models.TextChoices):
    VERIFIED = 'verified', 'Verified'
    CORROBORATED = 'corroborated', 'Corroborated'
    UNVERIFIED = 'unverified', 'Unverified'
    UNCONFIRMED = 'unconfirmed', 'Unconfirmed'


class AlertRisk(models.TextChoices):
    CRITICAL = 'critical', 'Critical'
    HIGH = 'high', 'High'
    MEDIUM = 'medium', 'Medium'
    LOW = 'low', 'Low'


class BriefingStatus(models.TextChoices):
    DRAFT = 'draft', 'Draft'
    PUBLISHED = 'published', 'Published'


# ─── Trust Score (cached per signal) ──────────────────────────────────

class TrustScore(models.Model):
    """
    Cached composite trust assessment for a sentinel Signal.
    Recomputed on each ingestion cycle by trust_engine.
    """
    signal = models.OneToOneField(
        Signal,
        on_delete=models.CASCADE,
        related_name='trust',
    )
    # Composite score 0-100
    score = models.IntegerField(default=0)
    trust_level = models.CharField(
        max_length=20,
        choices=TrustLevel.choices,
        default=TrustLevel.UNCONFIRMED,
    )

    # Component scores for transparency
    source_tier_weight = models.FloatField(default=0.0)
    corroboration_count = models.IntegerField(default=0)
    disease_match_confidence = models.IntegerField(default=0)
    recency_factor = models.FloatField(default=0.0)

    computed_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'hdis_pro_trustscore'
        ordering = ['-score']

    def __str__(self):
        return f"Trust {self.signal_id}: {self.trust_level} ({self.score})"


# ─── Alert ────────────────────────────────────────────────────────────

class Alert(models.Model):
    """
    Auto-generated alert when a signal crosses deterministic thresholds.
    Linked to a sentinel Signal (not AI-generated).
    """
    signal = models.ForeignKey(
        Signal,
        on_delete=models.CASCADE,
        related_name='hdis_alerts',
    )
    risk_level = models.CharField(
        max_length=20,
        choices=AlertRisk.choices,
        default=AlertRisk.MEDIUM,
    )
    trigger_reason = models.TextField()
    confidence_score = models.FloatField(default=0.0)
    signal_strength = models.IntegerField(default=1)  # 1-5
    multi_source_validated = models.BooleanField(default=False)

    # Acknowledgement
    acknowledged_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='acknowledged_alerts',
    )
    acknowledged_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'hdis_pro_alert'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['risk_level']),
            models.Index(fields=['-created_at']),
        ]

    def __str__(self):
        return f"[{self.risk_level}] {self.trigger_reason[:80]}"


# ─── Briefing ─────────────────────────────────────────────────────────

class BriefingScope(models.TextChoices):
    DAILY_GLOBAL = 'daily_global', 'Daily Global (All AFRO)'
    COUNTRY_FOCUS = 'country_focus', 'Country Focus'
    CRISIS_ALERT = 'crisis_alert', 'Crisis Alert'


class ConfidenceLevel(models.TextChoices):
    HIGH = 'high', 'High'
    MEDIUM = 'medium', 'Medium'
    LOW = 'low', 'Low'


class Briefing(models.Model):
    """
    AI-assisted executive briefing.
    Generated by the 4-agent pipeline (Gatherer → Analyst → Verifier → Composer).
    Must be published before visible to readers.
    """

    # ── Classification ────────────────────────────────────────────────
    briefing_type = models.CharField(max_length=50, default='daily')  # daily, weekly
    scope = models.CharField(
        max_length=20,
        choices=BriefingScope.choices,
        default=BriefingScope.DAILY_GLOBAL,
    )
    country_iso = models.CharField(
        max_length=3, blank=True, default='',
        help_text="ISO3 code for country-focus briefings",
    )

    # ── Content ───────────────────────────────────────────────────────
    content = models.JSONField(default=dict)
    # Structured JSON: {
    #   executive_summary, risk_assessment, cross_pillar_correlation,
    #   recommended_actions[], information_gaps[], open_actions[],
    #   sources_summary
    # }

    # ── Quality metadata ──────────────────────────────────────────────
    confidence_level = models.CharField(
        max_length=10,
        choices=ConfidenceLevel.choices,
        default=ConfidenceLevel.MEDIUM,
    )
    signal_count = models.IntegerField(default=0, help_text="Signals analyzed")
    source_count = models.IntegerField(default=0, help_text="Distinct sources used")
    generation_time_ms = models.IntegerField(default=0, help_text="Pipeline exec ms")
    llm_model = models.CharField(
        max_length=100, blank=True, default='',
        help_text="LLM model used for generation",
    )

    # ── Pipeline audit data ───────────────────────────────────────────
    # Store each agent's raw output for debugging/audit
    pipeline_data = models.JSONField(
        default=dict, blank=True,
        help_text="Raw output from each pipeline stage for audit",
    )
    # Structure: {
    #   gatherer: { signals_count, history_count, ... },
    #   analyst: { raw LLM response },
    #   verifier: { claims verified, flags, contradictions },
    #   composer: { raw LLM response },
    #   timings: { gatherer_ms, analyst_ms, verifier_ms, composer_ms }
    # }

    # ── Workflow ──────────────────────────────────────────────────────
    status = models.CharField(
        max_length=20,
        choices=BriefingStatus.choices,
        default=BriefingStatus.DRAFT,
    )
    country_filter = models.JSONField(default=list, blank=True)
    generated_by = models.CharField(max_length=100, default='system')
    published_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='published_briefings',
    )

    period_start = models.DateTimeField(null=True, blank=True)
    period_end = models.DateTimeField(null=True, blank=True)
    generated_at = models.DateTimeField(auto_now_add=True)

    # Tenant — added in migration 0005_add_tenant_fk but never declared on the
    # Python class. Briefing creation passes tenant=... so the class must
    # accept it as a real field.
    tenant = models.ForeignKey(
        'account.Tenant',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='briefings',
        help_text='Tenant for RLS. Populated from country_iso; global briefings → AFR.',
    )

    class Meta:
        db_table = 'hdis_pro_briefing'
        ordering = ['-generated_at']

    def __str__(self):
        scope_label = self.country_iso or self.get_scope_display()
        return f"{self.briefing_type} briefing ({self.status}) — {scope_label} — {self.generated_at:%Y-%m-%d}"


class JobStatus(models.TextChoices):
    """Status of a briefing generation job."""
    PENDING = 'pending', 'Pending'
    GATHERING = 'gathering', 'Gathering Signals'
    ANALYZING = 'analyzing', 'LLM Analysis'
    VERIFYING = 'verifying', 'Verification'
    COMPOSING = 'composing', 'Composing Briefing'
    COMPLETE = 'complete', 'Complete'
    FAILED = 'failed', 'Failed'


class BriefingGenerationJob(models.Model):
    """
    Tracks the status of a briefing generation pipeline run.
    Replaces the unreliable in-memory _generation_status dict.
    Persists across server restarts and works with multiple workers.
    """
    scope = models.CharField(max_length=30, default='daily_global')
    country_iso = models.CharField(max_length=3, blank=True, default='')
    hours_back = models.IntegerField(default=48)

    status = models.CharField(
        max_length=20,
        choices=JobStatus.choices,
        default=JobStatus.PENDING,
    )
    error = models.TextField(blank=True, default='')
    briefing = models.ForeignKey(
        Briefing, on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='generation_jobs',
    )

    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    requested_by = models.CharField(max_length=100, default='system')

    # Tenant — added in migration 0005_add_tenant_fk but never declared in
    # the Python class. Declared here so it can be referenced by the
    # tenant-scoped unique constraint below.
    tenant = models.ForeignKey(
        'account.Tenant',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='generation_jobs',
        help_text='Tenant for RLS. Populated from country_iso; global jobs → AFR.',
    )

    # Singleton lock: set to 'running' while the job is in-flight, NULL after
    # it completes or fails. Combined with the unique constraint below, this
    # guarantees at most one concurrent briefing-generation job at the DB layer
    # (multiple NULLs are permitted by the unique index).
    lock_key = models.CharField(max_length=20, null=True, blank=True, default='running')

    class Meta:
        db_table = 'hdis_pro_generation_job'
        ordering = ['-started_at']
        constraints = [
            # Tenant-scoped singleton: each tenant may have at most one row
            # with lock_key='running' at any time. NULL lock_keys (finished
            # jobs) are exempt because Postgres treats NULLs as distinct in
            # unique indexes.
            models.UniqueConstraint(
                fields=['tenant', 'lock_key'],
                name='only_one_running_briefing_job_per_tenant',
            ),
        ]

    def __str__(self):
        return f"Job #{self.id} ({self.status}) — {self.scope} — {self.started_at:%H:%M}"

    @property
    def is_running(self) -> bool:
        return self.status in (
            JobStatus.PENDING, JobStatus.GATHERING,
            JobStatus.ANALYZING, JobStatus.VERIFYING,
            JobStatus.COMPOSING,
        )

    def mark_stage(self, stage: str):
        """Update the job stage and save."""
        self.status = stage
        self.save(update_fields=['status'])

    def mark_complete(self, briefing: 'Briefing'):
        """Mark job as complete with the resulting briefing."""
        self.status = JobStatus.COMPLETE
        self.briefing = briefing
        self.completed_at = timezone.now()
        self.lock_key = None
        self.save(update_fields=['status', 'briefing', 'completed_at', 'lock_key'])

    def mark_failed(self, error: str):
        """Mark job as failed with error message."""
        self.status = JobStatus.FAILED
        self.error = error[:2000]
        self.completed_at = timezone.now()
        self.lock_key = None
        self.save(update_fields=['status', 'error', 'completed_at', 'lock_key'])
