# Generated by Django 4.2.4 on 2026-05-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentinel', '0012_alter_signal_source_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_id', models.IntegerField(db_index=True, help_text='Kobo _id — unique numeric submission ID', unique=True)),
                ('kobo_uuid', models.CharField(help_text='Kobo _uuid — unique submission UUID', max_length=100, unique=True)),
                ('xform_id_string', models.CharField(default='', help_text='Kobo _xform_id_string — asset UID this submission belongs to', max_length=200)),
                ('form_version', models.CharField(default='', help_text='Kobo __version__ — form version at time of submission', max_length=100)),
                ('chw_name', models.CharField(default='', help_text='Full name of the CHW (PII — admin-only)', max_length=200)),
                ('chw_clinic', models.CharField(default='', help_text='Clinic or hospital the CHW is affiliated with', max_length=300)),
                ('description', models.TextField(default='', help_text='Free-text description of what the CHW observed')),
                ('event_type', models.CharField(default='', help_text='Space-separated values from health_event_type list', max_length=500)),
                ('event_other', models.CharField(default='', help_text='Free-text for "other" event type', max_length=300)),
                ('case_count', models.IntegerField(default=0, help_text='Estimated number of people affected (cast from string)')),
                ('age_group', models.CharField(default='', help_text='Age group most affected (from age_group list)', max_length=50)),
                ('severity', models.CharField(default='', help_text='Severity level (from severity list)', max_length=50)),
                ('gps_location', models.CharField(default='', help_text='Raw GPS string "lat lon altitude accuracy" from device', max_length=200)),
                ('text_location', models.TextField(default='', help_text='Free-text community/village/region/country description')),
                ('adm0_pcode', models.CharField(default='', help_text='Country P-code (ISO 3166-1 alpha-2)', max_length=10)),
                ('adm0_name', models.CharField(default='', help_text='Country name (geocoded)', max_length=200)),
                ('adm1_pcode', models.CharField(default='', help_text='Admin level 1 P-code (province/state)', max_length=20)),
                ('adm1_name', models.CharField(default='', help_text='Admin level 1 name', max_length=200)),
                ('adm2_pcode', models.CharField(default='', help_text='Admin level 2 P-code (territory/district)', max_length=20)),
                ('adm2_name', models.CharField(default='', help_text='Admin level 2 name', max_length=200)),
                ('geocoded_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Geocoded latitude from text_location', max_digits=10, null=True)),
                ('geocoded_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Geocoded longitude from text_location', max_digits=10, null=True)),
                ('geocoding_confidence', models.CharField(default='', help_text='Geocoding match confidence level', max_length=50)),
                ('photo_evidence', models.CharField(default='', help_text='Filename of uploaded photo', max_length=500)),
                ('comments_text', models.TextField(default='', help_text='Additional text comments from CHW')),
                ('comments_audio', models.CharField(default='', help_text='Filename of audio comment', max_length=500)),
                ('whatsapp_number', models.CharField(default='', help_text='Sender WhatsApp number (PII — admin-only)', max_length=50)),
                ('whatsapp_transcript', models.TextField(default='', help_text='Full bot-CHW conversation transcript (PII — admin-only)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Kobo _submission_time — when the server received the submission', null=True)),
                ('submitted_by', models.CharField(default='', help_text='Kobo _submitted_by — username of submitter', max_length=200)),
                ('submission_status', models.CharField(default='', help_text='Kobo _status (e.g. submitted_via_web)', max_length=100)),
                ('anomaly_flag', models.BooleanField(default=False, help_text='Flagged for review when case_count > 1000')),
                ('raw_payload', models.JSONField(default=dict, help_text='Full raw JSON payload from KoboToolbox API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(blank=True, help_text='The sentinel.Signal created from this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kobo_submission', to='sentinel.signal')),
            ],
            options={
                'verbose_name': 'Kobo Submission',
                'verbose_name_plural': 'Kobo Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['event_type'], name='kobo_kobosu_event_t_04327e_idx'), models.Index(fields=['severity'], name='kobo_kobosu_severit_b9c85a_idx'), models.Index(fields=['-submitted_at'], name='kobo_kobosu_submitt_e7964f_idx')],
            },
        ),
    ]
