# Generated by Django 4.2.4 on 2025-11-19 13:19

import account.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default=account.models.generate_token, max_length=64, unique=True)),
                ('refresh_token', models.CharField(default=account.models.generate_token, max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('user_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('phone_number', models.CharField(error_messages={'required': 'We need your phone to onboard you.', 'unique': 'This phone number is already registered'}, help_text='Enter your Number in international format, e.g. +234XXXXXXXXXX', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +234xxxxxxxxxx. Up to 15 digits allowed.', regex='^\\+\\d{6,15}$')])),
                ('country', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('has_accepted_terms', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('lock_count', models.PositiveIntegerField(default=0)),
                ('lock_duration', models.DateTimeField(blank=True, null=True)),
                ('last_email_change', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
