# Generated by Django 4.2.4 on 2025-12-06 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('acknowledge', 'acknowledge'), ('resolved', 'resolved')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'CRITICAL'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledge_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
