# Generated by Django 4.2.4 on 2025-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alerts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
