# Generated by Django 4.2.4 on 2025-12-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_alert_acknowledge_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('disease_outbreak', 'Disease Outbreak'), ('resource_shortage', 'Resource Shortage'), ('natural_disaster', 'Natural Disaster'), ('administrative', 'Administrative'), ('capaticy_alert', 'Capacity Alert')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved')], max_length=50),
        ),
    ]
