# Generated by Django 4.2.4 on 2026-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_alert_category_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customauthtoken',
            name='device_info',
            field=models.CharField(blank=True, help_text='Browser/Device information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customauthtoken',
            name='browser_session_id',
            field=models.CharField(blank=True, help_text='Unique browser session identifier', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customauthtoken',
            name='last_used',
            field=models.DateTimeField(auto_now=True, help_text='Last time this token was used'),
        ),
        migrations.AddIndex(
            model_name='customauthtoken',
            index=models.Index(fields=['user_type', 'user_id'], name='account_cus_user_ty_8e0e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='customauthtoken',
            index=models.Index(fields=['access_token'], name='account_cus_access__9f8b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customauthtoken',
            index=models.Index(fields=['refresh_token'], name='account_cus_refresh_4a7c2d_idx'),
        ),
        migrations.AlterModelOptions(
            name='customauthtoken',
            options={'ordering': ['-created']},
        ),
    ]
