# Generated by Django 4.2.4 on 2026-02-19 10:23
# Fixed: RenameIndex fails on fresh DB. Using safe RunSQL with IF EXISTS.

from django.db import migrations


def safe_rename_indexes(apps, schema_editor):
    """Safely rename indexes — skip if old name doesn't exist (fresh DB)."""
    if schema_editor.connection.vendor == 'postgresql':
        renames = [
            ('account_cus_user_ty_8e0e3a_idx', 'account_cus_user_ty_9f7392_idx'),
            ('account_cus_access__9f8b3c_idx', 'account_cus_access__38519b_idx'),
            ('account_cus_refresh_4a7c2d_idx', 'account_cus_refresh_ceaa86_idx'),
        ]
        for old_name, new_name in renames:
            try:
                schema_editor.execute(
                    f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}"'
                )
            except Exception:
                pass  # Index doesn't exist — fresh DB or already renamed


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_add_multidevice_support'),
    ]

    operations = [
        migrations.RunPython(safe_rename_indexes, migrations.RunPython.noop),
    ]
