# Generated by Django 6.0.2 on 2026-02-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_add_multidevice_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RenameIndex(
            model_name='customauthtoken',
            new_name='account_cus_user_ty_9f7392_idx',
            old_name='account_cus_user_ty_8e0e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='customauthtoken',
            new_name='account_cus_access__38519b_idx',
            old_name='account_cus_access__9f8b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='customauthtoken',
            new_name='account_cus_refresh_ceaa86_idx',
            old_name='account_cus_refresh_4a7c2d_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.role'),
        ),
    ]
