# Generated by Django 4.2.4 on 2026-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_account_cus_user_ty_8e0e3a_idx_account_cus_user_ty_9f7392_idx_and_more'),
        ('account', '0008_role_and_more'),
    ]

    operations = [
    ]
