# Generated by Django 4.2.4 on 2026-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20260225_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User'), ('supplier', 'Supplier'), ('department', 'Department')], max_length=50, unique=True),
        ),
    ]
