# Generated by Django 4.2.4 on 2026-02-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20260222_2346'),
        ('account', '0010_alter_role_name'),
    ]

    operations = [
    ]
