# Generated by Django 4.2.4 on 2026-04-05 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_0009_merge_20260222_2346_0010_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, default='', help_text='Snapshot of user email at audit time (survives user deletion)', max_length=255)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('data_upload', 'Data Upload'), ('data_delete', 'Data Delete'), ('data_export', 'Data Export'), ('form_generate', 'Form Generate'), ('form_submit', 'Form Submit'), ('form_delete', 'Form Delete'), ('report_create', 'Report Create'), ('report_update', 'Report Update'), ('report_delete', 'Report Delete'), ('link_generate', 'Link Generate'), ('link_reactivate', 'Link Reactivate'), ('alert_acknowledge', 'Alert Acknowledge'), ('alert_resolve', 'Alert Resolve'), ('admin_action', 'Admin Action')], db_index=True, max_length=30)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], default='success', max_length=10)),
                ('detail', models.TextField(blank=True, default='', help_text='Human-readable description of what happened')),
                ('resource_type', models.CharField(blank=True, default='', help_text='Model/entity type, e.g. "StarData", "WeeklyReport"', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', help_text='Primary key or identifier of the resource', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('http_method', models.CharField(blank=True, default='', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous/failed logins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='account_aud_user_id_57d347_idx'), models.Index(fields=['action', 'timestamp'], name='account_aud_action_739f83_idx'), models.Index(fields=['endpoint'], name='account_aud_endpoin_ca1652_idx')],
            },
        ),
    ]
