# Generated by Django 4.2.4 on 2026-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_add_audit_log_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('data_upload', 'Data Upload'), ('data_delete', 'Data Delete'), ('data_export', 'Data Export'), ('form_generate', 'Form Generate'), ('form_submit', 'Form Submit'), ('form_delete', 'Form Delete'), ('report_create', 'Report Create'), ('report_update', 'Report Update'), ('report_delete', 'Report Delete'), ('link_generate', 'Link Generate'), ('link_reactivate', 'Link Reactivate'), ('alert_acknowledge', 'Alert Acknowledge'), ('alert_resolve', 'Alert Resolve'), ('admin_action', 'Admin Action')], db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='endpoint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='http_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='outcome',
            field=models.TextField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], default='success'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.TextField(blank=True, default='', help_text='Primary key or identifier of the resource'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.TextField(blank=True, default='', help_text='Model/entity type, e.g. "StarData", "WeeklyReport"'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_email',
            field=models.TextField(blank=True, default='', help_text='Snapshot of user email at audit time (survives user deletion)'),
        ),
    ]
