# Generated by Django 4.2.4 on 2026-04-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_charfield_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name, e.g. Nigeria', max_length=100, unique=True)),
                ('iso_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-3, e.g. NGA', max_length=3, unique=True)),
                ('is_continental', models.BooleanField(default=False, help_text='True only for the AFRO HQ continental tenant (super admin scope)')),
                ('is_active', models.BooleanField(default=True)),
                ('who_region', models.CharField(blank=True, default='', help_text='WHO sub-region, e.g. West Africa', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The country/tenant this user belongs to. Null = unassigned (legacy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.tenant'),
        ),
    ]
