# Generated by Django 4.2.4 on 2026-05-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_enable_rls_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sso_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time user profile was synced from the Identity Provider', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_provider',
            field=models.CharField(blank=True, help_text='SSO provider name, e.g. "microsoft"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_uid',
            field=models.CharField(blank=True, help_text='SSO subject (sub) claim — unique ID from the Identity Provider', max_length=255, null=True),
        ),
    ]
