# Generated by Django 4.2.4 on 2026-01-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IhmrefCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('simulation_exercise', 'Simulation Exercises'), ('after_action_review', 'After Action Reviews'), ('intra_action_review', 'Intra Action Reviews'), ('early_action_review', 'Early Action Reviews'), ('naphs', 'NAPHS'), ('nbws', 'NBWS'), ('jee', 'JEE'), ('risk_profiling', 'Risk Profiling')])),
            ],
        ),
        migrations.CreateModel(
            name='IhmrefDataSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afro', models.IntegerField(default=0)),
                ('global_t', models.IntegerField(default=0)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihmref.ihmrefcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IhmrefData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('afro', models.IntegerField(default=0)),
                ('global_t', models.IntegerField(default=0)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_african_countries', models.IntegerField(default=0)),
                ('african_countries_involved', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ihmref_category', to='ihmref.ihmrefcategory')),
            ],
        ),
    ]
