# Generated by Django 4.2.4 on 2026-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihmref', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihmrefdata',
            name='african_countries_involved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
