# Generated by Django 4.2.4 on 2026-01-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihmref', '0002_alter_ihmrefdata_african_countries_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='IhmrefCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('country', 'state')},
            },
        ),
        migrations.CreateModel(
            name='CountryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihmref.ihmrefcountry')),
                ('ihmref_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihmref.ihmrefdata')),
            ],
        ),
    ]
