# Generated by Django 4.2.4 on 2026-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihmref', '0003_ihmrefcountry_countryincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryincident',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryincident',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ihmrefcountry',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ihmrefcountry',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
