# Generated by Django 4.2.4 on 2026-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihmref', '0004_alter_countryincident_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihmrefcategory',
            name='category',
            field=models.CharField(choices=[('simulation_exercise', 'Simulation Exercises'), ('after_action_review', 'After Action Reviews'), ('intra_action_review', 'Intra Action Reviews'), ('early_action_review', 'Early Action Reviews'), ('naphs', 'NAPHS'), ('nbws', 'NBWS'), ('jee', 'JEE'), ('risk_profiling', 'Risk Profiling')], max_length=255),
        ),
    ]
