# Generated by Django 4.2.4 on 2026-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihmref', '0005_alter_ihmrefcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihmrefcategory',
            name='category',
            field=models.CharField(choices=[('simulation_exercise', 'Simulation Exercises'), ('after_action_review', 'After Action Reviews'), ('intra_action_review', 'Intra Action Reviews'), ('early_action_review', 'Early Action Reviews'), ('naphs', 'NAPHS'), ('nbws', 'NBWS'), ('jee', 'JEE'), ('risk_profiling', 'Risk Profiling')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ihmrefcountry',
            name='country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ihmrefcountry',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ihmrefcountry',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
