# Generated by Django 4.2.4 on 2026-04-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihmref', '0006_alter_ihmrefcategory_category'),
        ('ihmref', '0006_charfield_to_textfield'),
    ]

    operations = [
    ]
