# Generated by Django 4.2.4 on 2026-04-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_add_tenant_model_and_user_fk'),
        ('ihmref', '0007_merge_20260409_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihmrefcountry',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Country tenant for RLS (populated from country name).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihmref_countries', to='account.tenant'),
        ),
    ]
