# Generated by Django 4.2.4 on 2026-04-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_populate_all_tenants'),
        ('ihmref', '0008_add_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryincident',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from country.tenant for direct RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihmref_incidents', to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='ihmrefcountry',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Country tenant. Populated from normalized country name; non-African -> AFR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihmref_countries', to='account.tenant'),
        ),
    ]
