# Generated by Django 4.2.4 on 2026-03-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(blank=True, default='', max_length=3)),
                ('population_2024', models.BigIntegerField(default=0)),
                ('total_chws', models.IntegerField(default=0)),
                ('chws_per_10000', models.FloatField(default=0.0)),
                ('total_regions', models.IntegerField(default=0)),
                ('total_districts', models.IntegerField(default=0)),
                ('total_facilities', models.IntegerField(default=0)),
                ('data_year', models.IntegerField(default=2026)),
                ('data_date', models.CharField(blank=True, default='', max_length=50)),
                ('data_source', models.CharField(blank=True, default='', max_length=500)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
                ('admin_level', models.CharField(default='district', help_text='district, council, commune, payam, boma, préfecture', max_length=50)),
                ('total_chws', models.IntegerField(default=0)),
                ('chw_count', models.IntegerField(default=0)),
                ('population', models.BigIntegerField(default=0)),
                ('population_est', models.BigIntegerField(default=0)),
                ('households', models.IntegerField(default=0)),
                ('chws_per_10k', models.FloatField(default=0.0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.country')),
            ],
            options={
                'ordering': ['country', 'region', 'district_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200)),
                ('admin_level', models.CharField(default='region', help_text='region, province, state, zone, island, département', max_length=50)),
                ('total_chws', models.IntegerField(default=0)),
                ('total_population', models.BigIntegerField(default=0)),
                ('total_facilities', models.IntegerField(default=0)),
                ('district_count', models.IntegerField(default=0)),
                ('region_number', models.IntegerField(default=0)),
                ('province', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.country')),
            ],
            options={
                'ordering': ['country', 'region_name'],
                'unique_together': {('country', 'region_name')},
            },
        ),
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chwfolder.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chwfolder.region')),
            ],
            options={
                'ordering': ['country', 'worker_type'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(default='Unknown', max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('facility_name', models.CharField(blank=True, default='', max_length=300)),
                ('facility_code', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ownership', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chwfolder.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chwfolder.region')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['country', 'facility_type'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chwfolder.region'),
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_imported', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chwfolder.country')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
