# Generated by Django 4.2.4 on 2026-04-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_add_tenant_model_and_user_fk'),
        ('chwfolder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Country tenant for RLS (populated from iso_code).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_countries', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from parent Country.tenant for RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_uploads', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='district',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from parent Country.tenant for RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_districts', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from parent Country.tenant for RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_facilities', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='region',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from parent Country.tenant for RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_regions', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='workertype',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from parent Country.tenant for RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_worker_types', to='account.tenant'),
        ),
    ]
