# Generated by Django 4.2.4 on 2026-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chwfolder', '0003_enable_rls_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='active_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='active_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='country',
            name='data_flag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='inactive_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='paid_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='volunteer_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='active_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='active_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='district',
            name='data_flag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='district',
            name='inactive_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='paid_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='volunteer_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='active_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='active_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='region',
            name='data_flag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='inactive_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='paid_chws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='volunteer_chws',
            field=models.IntegerField(default=0),
        ),
    ]
