# Generated by Django 4.2.4 on 2025-11-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_on_table', models.CharField(max_length=100, unique=True)),
                ('data_received', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('states', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=10)),
                ('total_average', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('value', models.IntegerField()),
                ('espar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='espar.espar')),
            ],
        ),
        migrations.AddField(
            model_name='espar',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='espar.sheet'),
        ),
        migrations.AlterUniqueTogether(
            name='espar',
            unique_together={('sheet', 'key_on_table')},
        ),
    ]
