# Generated by Django 4.2.4 on 2025-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('espar', 'code')},
        ),
    ]
