# Generated by Django 4.2.4 on 2025-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espar', '0002_alter_indicator_code_alter_indicator_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espar',
            name='total_average',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
