# Generated by Django 4.2.4 on 2025-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espar', '0003_alter_espar_total_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
