# Generated by Django 4.2.4 on 2026-04-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_add_tenant_model_and_user_fk'),
        ('espar', '0004_alter_indicator_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='espar',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Country tenant for RLS (populated from iso_code).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espar_data', to='account.tenant'),
        ),
    ]
