# Generated by Django 4.2.4 on 2026-04-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_populate_all_tenants'),
        ('espar', '0005_add_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from espar.tenant for direct RLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espar_indicators', to='account.tenant'),
        ),
    ]
