## Automatically generated by odin 1.5.11 - do not edit
seirdv_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "seirdv_rhs_dde"),
    dll = "wbepi",
    user = c("beta", "delta", "gamma", "ini_D", "ini_E", "ini_I", "ini_R",
             "ini_S", "ini_V", "interv_delay", "interv_efficacy",
             "interv_release", "interv_vacc_coverage", "interv_vacc_type",
             "mu", "n_populations", "sigma", "target_size", "vacc_coverage",
             "vacc_efficacy"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("seirdv_rhs_dde", package = "wbepi")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("seirdv_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "wbepi")
    },

    update_metadata = function() {
      meta <- .Call("seirdv_metadata", private$ptr,
                    PACKAGE = "wbepi")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("seirdv_create", user, PACKAGE = "wbepi")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/seirdv.json", mustWork = TRUE,
                             package = "wbepi")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("seirdv_set_user", private$ptr, user, PACKAGE = "wbepi")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("seirdv_initial_conditions", private$ptr, step, PACKAGE = "wbepi")
    },

    rhs = function(step, y) {
      .Call("seirdv_rhs_r", private$ptr, step, y, PACKAGE = "wbepi")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("seirdv_contents", private$ptr, PACKAGE = "wbepi")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


seirdv <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("seirdv")
  seirdv_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(seirdv) <- "odin_generator"
attr(seirdv, "generator") <- seirdv_
