# WHO AFRO Region Countries
# Official list of 47 WHO African Regional Office member states
# Note: Algeria, Egypt, Libya, Morocco, Tunisia belong to EMRO (Eastern Mediterranean), not AFRO

AFRO_COUNTRIES = [
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Côte d'Ivoire",
    "Democratic Republic of the Congo",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "São Tomé and Príncipe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "South Africa",
    "South Sudan",
    "Togo",
    "Uganda",
    "United Republic of Tanzania",
    "Zambia",
    "Zimbabwe",
]

# Lowercase version for case-insensitive matching
AFRO_COUNTRIES_LOWER = [c.lower() for c in AFRO_COUNTRIES]
