BASE_FIELDS = {"Data Received", "Region", "States Party of IHR", "ISO Code", "Total Average" }
CAPACITIES = {
    "C.1.1": "Policy, legal and normative instruments",
    "C.1.2": "Gender Equality in health emergencies",
    "C.1": "Policy, Legal and normative Instruments to implement IHR",
    "C.2.1": "National IHR Focal Point functions",
    "C.2.2": "Multisectoral IHR coordination mechanisms",
    "C.2.3": "Advocacy for IHR implementation",
    "C.2": "IHR Coordination, National IHR Focal Point functions and advocacy",
    "C.3.1": "Financing for IHR implementation",
    "C.3.2": "Financing for Public Health Emergency Response",
    "C.3": "Financing",
    "C.4.1": "Specimen referral and transport system",
    "C.4.2": "Implementation of a laboratory biosafety and biosecurity regime",
    "C.4.3": "Laboratory quality system",
    "C.4.4": "Laboratory testing capacity modalities",
    "C.4.5": "Effective national diagnostic network",
    "C.4": "Laboratory",
    "C.5.1": "Early warning surveillance function",
    "C.5.2": "Event management (i.e., verification, investigation, analysis, and dissemination of information)",
    "C.5": "Surveillance",
    "C.6.1": "Human resources for implementation of IHR",
    "C.6.2": "Workforce surge during a public health event",
    "C.6": "Human resources",
    "C.7.1": "Planning for health emergencies",
    "C.7.2": "Management of health emergency response",
    "C.7.3": "Emergency logistic and supply chain management",
    "C.7": "Health emergency management",
    "C.8.1": "Case management",
    "C.8.2": "Utilization of health services",
    "C.8.3": "Continuity of essential health services (EHS)",
    "C.8": "Health services provision",
    "C.9.1": "IPC programmes",
    "C.9.2": "Health care-associated infections (HCAI) surveillance",
    "C.9.3": "Safe environment in health facilities",
    "C.9": "Infection prevention and control (IPC)",
    "C.10.1": "RCCE system for emergencies",
    "C.10.2": "Risk communication",
    "C.10.3": "Community engagement",
    "C.10": "Risk communication and community engagement (RCCE)",
    "C.11.1": "Core capacity requirements at all times for PoEs (airports, ports and ground crossings)",
    "C.11.2": "Public health response at points of entry",
    "C.11.3": "Risk-based approach to international travel-related measures",
    "C.11": "Points of entry (PoEs) and border health",
    "C.12.1": "One Health collaborative efforts across sectors on activities to address zoonoses",
    "C.12": "Zoonotic diseases",
    "C.13.1": "Multisectoral collaboration mechanism for food safety events",
    "C.13": "Food safety",
    "C.14.1": "Resources for detection and alert",
    "C.14": "Chemical events",
    "C.15.1": "Capacity and resources",
    "C.15": "Radiation emergencies",
}

# Official WHO African Regional Office (AFRO) Countries
# Source: WHO AFRO Member States (47 countries)
AFRO_COUNTRIES = [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Côte d'Ivoire",
    "Democratic Republic of the Congo",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "São Tomé and Príncipe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "South Africa",
    "South Sudan",
    "Togo",
    "Uganda",
    "United Republic of Tanzania",
    "Zambia",
    "Zimbabwe",
]
